'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'am' | 'om' | 'ti';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.groups': 'Groups',
    'nav.receipts': 'Receipts',
    'nav.lottery': 'Lottery',
    'nav.rules': 'Rule Templates',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.admin_panel': 'Admin Dashboard',
    // Dashboard Page
    'db.title': 'Dashboard',
    'db.subtitle': 'Overview of your Equb platform activity',
    'db.loading': 'Loading dashboard...',
    'db.stat_groups': 'Total Groups',
    'db.stat_members': 'Active Members',
    'db.stat_receipts': 'Pending Receipts',
    'db.stat_collected': 'Total Collected',
    'db.chart_title': 'Deposits Over Time',
    'db.chart_subtitle': 'Monthly deposit and verification trends',
    'db.chart_no_data': 'No deposit data available yet.',
    'db.chart_total': 'Total Deposits',
    'db.chart_verified': 'Verified',
    'db.activity_title': 'Recent Activity',
    'db.activity_view_all': 'View all',
    'db.activity_no_data': 'No recent activity.',
    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and security',
    'settings.change_pwd': 'Change Password',
    'settings.update_pwd_desc': 'Update your admin account password',
    'settings.curr_pwd': 'Current Password',
    'settings.new_pwd': 'New Password',
    'settings.confirm_pwd': 'Confirm New Password',
    'settings.sec_note': 'Choose a strong password with at least 6 characters.',
    'settings.btn_change': 'Change Password',
    'settings.lang_select': 'System Language',
    'settings.lang_desc': 'Choose your preferred language for the dashboard display',
    // Groups page
    'groups.title': 'Equb Groups',
    'groups.subtitle': 'Manage all rotating savings groups',
    'groups.create_btn': 'Create Group',
    'groups.search_placeholder': 'Search groups...',
    'groups.members': 'Members',
    'groups.contribution': 'Contribution',
    'groups.cycle': 'Cycle',
    'groups.progress': 'Progress',
    'groups.no_groups': 'No groups found',
    'groups.no_groups_desc': 'Get started by creating your first Equb group.',
    'groups.no_groups_match': 'No groups match your search.',
    'groups.loading': 'Loading groups...',
    'groups.success_create': 'Equb group created successfully!',
    'groups.modal_title': 'Create New Equb Group',
    'groups.label_name': 'Group Name',
    'groups.label_amount': 'Contribution (ETB)',
    'groups.label_max_members': 'Max Members',
    'groups.label_duration': 'Cycle Duration',
    'groups.label_description': 'Description (Optional)',
    'groups.btn_cancel': 'Cancel',
    'groups.btn_create': 'Create Group',
    // Group Details page
    'group.draw_lottery': 'Draw Lottery',
    'group.back_to_groups': 'Back to Groups',
    'group.not_found': 'Group not found',
    'group.not_found_desc': "This group doesn't exist or you don't have permission to view it.",
    'group.loading': 'Loading group details...',
    'group.tab_deposits': 'Current Cycle Deposits',
    'group.tab_members': 'Members',
    'group.tab_rules': 'Rules & Settings',
    'group.col_member': 'Member',
    'group.col_amount': 'Amount',
    'group.col_date': 'Date',
    'group.col_status': 'Status',
    'group.col_actions': 'Actions',
    'group.no_deposits': 'No deposits for the current cycle yet.',
    'group.active_members': 'active member',
    'group.active_members_plural': 'active members',
    'group.add_member': 'Add Member',
    'group.col_won': 'Won',
    'group.col_cycle_won': 'Cycle Won',
    'group.no_members': 'No members in this group yet.',
    'group.add_first_member': 'Add First Member',
    'group.rules_loading': 'Loading rules...',
    'group.rules_title': 'Rule Templates',
    'group.rules_subtitle': 'Load a saved template or save current rules as a new template',
    'group.save_template': 'Save as Template',
    'group.save_changes': 'Save Changes',
    // Group rules settings labels
    'group.rules_deposit': 'Deposit Rules',
    'group.rules_member': 'Member Rules',
    'group.rules_penalty': 'Penalty Settings',
    'group.rules_payout': 'Payout Configuration',
    'group.rules_governance': 'Governance',
    'group.rules_additional': 'Additional Rules',
    'group.rules_save': 'Save Rules',
    'group.rules_unable': 'Unable to load rules',
    'group.next_draw': 'Next Draw',
    'group.label_require_exact': 'Require Exact Amount',
    'group.label_require_gov_id': 'Require Government ID',
    'group.label_require_guarantor': 'Require Guarantor',
    'group.label_late_penalty': 'Late Payment Penalty',
    'group.label_max_skips': 'Max Skips Allowed',
    'group.label_allow_skip': 'Allow Skip Round',
    'group.label_admin_fee': 'Admin Fee',
    'group.label_admin_fee_type': 'Admin Fee Type',
    'group.label_payout_schedule': 'Payout Schedule',
    'group.label_early_withdrawal': 'Early Withdrawal Policy',
    'group.label_dispute_method': 'Dispute Resolution Method',
    'group.label_min_members': 'Min Members to Start',
    // Login page
    'login.title': 'Equb Admin',
    'login.subtitle': 'Digital Savings Platform',
    'login.welcome': 'Welcome back',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.savings': 'Savings Groups',
    'login.signin': 'Sign in',
    // Receipts extra
    'receipts.bank': 'Bank',
    'receipts.bank_name': 'Bank Name',
    'receipts.extracted_amount': 'Extracted Amount',
    // Lottery extra
    'lottery.eligible': 'Eligible',
    'lottery.col_winner': 'Winner',
    // Members extra (detail page)
    'member.col_group_name': 'Group Name',
    'member.col_amount_won': 'Amount Won',
    'member.save_changes': 'Save Changes',
    // Groups list
    'groups.frequency_weekly': 'Weekly',
    'groups.frequency_monthly': 'Monthly',
    // Receipts page
    'receipts.title': 'Receipts',
    'receipts.subtitle_pending': 'Verify deposit receipts',
    'receipts.filter': 'Filter:',
    'receipts.all_status': 'All Status',
    'receipts.pending': 'Pending',
    'receipts.verified': 'Verified',
    'receipts.rejected': 'Rejected',
    'receipts.all_groups': 'All Groups',
    'receipts.no_receipts': 'No receipts found',
    'receipts.no_receipts_desc': 'No receipts match the current filters or have been submitted yet.',
    'receipts.modal_title': 'Receipt Details',
    'receipts.ocr_title': 'OCR Extracted Data',
    'receipts.ocr_mismatch': '⚠️ Amount mismatch detected',
    'receipts.loading': 'Loading receipts...',
    'receipts.verify': 'Verify',
    'receipts.reject': 'Reject',
    'receipts.ocr_ref': 'Transaction Ref',
    'receipts.ocr_date': 'Extracted Date',
    'receipts.image_label': 'Receipt Image',
    'receipts.no_image': 'No image uploaded',
    'group.save_template_as': 'Save Rules as Template',
    'group.label_max_missed': 'Max Missed Payments',
    'group.label_max_missed_removal': 'Max Missed Payments Before Removal',
    'group.desc_skip_round': 'Members can skip a round',
    'group.desc_require_guarantor': 'Must have a guarantor to join',
    'group.desc_require_exact': 'Must match contribution exactly',
    // Lottery page
    'lottery.title': 'Lottery Draws',
    'lottery.subtitle': 'Manage and trigger lottery draws for equb groups',
    'lottery.draw_complete': '🎉 Draw Complete!',
    'lottery.trigger_draw': 'Trigger New Draw',
    'lottery.winner': 'Winner:',
    'lottery.gross_payout': 'Gross Payout Won:',
    'lottery.admin_fee': 'Admin Fee Deduction:',
    'lottery.net_payout': 'Net Member Payout:',
    'lottery.draw_again': 'Draw Again',
    'lottery.select_group': 'Select Group',
    'lottery.choose_group': 'Choose a group...',
    'lottery.draw_now': 'Draw Now',
    'lottery.past_results': 'Past Draw Results',
    'lottery.past_results_desc': 'History of all lottery draws across groups',
    'lottery.no_results': 'No lottery draws yet.',
    'lottery.loading': 'Loading lottery...',
    // Notifications page
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay updated on group activity, deadlines, and alerts',
    'notifications.mark_all': 'Mark All as Read',
    'notifications.loading': 'Loading notifications...',
    'notifications.all_caught_up': 'All caught up!',
    'notifications.no_read': 'No read notifications',
    'notifications.no_notifications': 'No notifications yet',
    'notifications.no_unread_desc': 'You have no unread notifications.',
    'notifications.no_read_desc': 'Notifications you have read will appear here.',
    'notifications.no_notifications_desc': 'Notifications about deadlines, deposits, and group activity will appear here.',
    // Rule Templates Page
    'rules.title': 'Rule Templates',
    'rules.subtitle': 'Manage and reuse rule configurations across groups',
    'rules.create_btn': 'Create Template',
    'rules.search_placeholder': 'Search templates by name or description...',
    'rules.no_templates': 'No rule templates yet',
    'rules.no_templates_desc': 'Create a template to save and reuse rule configurations across your groups.',
    'rules.no_templates_match': 'No matching templates',
    'rules.no_templates_match_desc': 'Try a different search term.',
    'rules.loading': 'Loading templates...',
    'rules.modal_create': 'Create Rule Template',
    'rules.modal_edit': 'Edit Rule Template',
    'rules.btn_cancel': 'Cancel',
    'rules.btn_create': 'Create Template',
    'rules.btn_save': 'Save Changes',
    'rules.label_name': 'Template Name *',
    'rules.label_desc': 'Description',
    'rules.label_desc_placeholder': 'Brief description of this template...',
    // Members & Member Detail Pages
    'members.title': 'Platform Members',
    'members.subtitle': 'Manage all platform members',
    'members.add_btn': 'Add Member',
    'members.search_placeholder': 'Search by name, phone, or Telegram ID...',
    'members.col_name': 'Name',
    'members.col_phone': 'Phone',
    'members.col_telegram': 'Telegram',
    'members.col_groups': 'Groups',
    'members.col_deposits': 'Total Deposits',
    'members.col_joined': 'Joined',
    'members.no_members': 'No members found',
    'members.no_members_desc': 'No members yet. Add your first member to get started.',
    'members.no_members_match': 'No members found matching your search.',
    'members.modal_title': 'Add New Member',
    'members.label_name': 'Full Legal Name *',
    'members.label_phone': 'Phone Number *',
    'members.label_gov_id': 'Government ID / Digital ID',
    'members.label_telegram': 'Telegram ID',
    'members.label_photo': 'Photo',
    'members.label_marital': 'Marital Status',
    'members.label_employment': 'Employment Type',
    'members.label_employer': 'Employer / Company Name',
    'members.label_country': 'Country',
    'members.label_city': 'City',
    'members.label_subcity': 'Sub City',
    'members.label_woreda': 'Woreda',
    'members.label_house': 'House Number',
    'members.basic_info': 'Basic Information',
    'members.personal_details': 'Personal Details',
    'members.address': 'Address',
    'members.btn_cancel': 'Cancel',
    'members.btn_add': 'Add Member',
    'members.success_create': 'Member added successfully!',
    'members.loading': 'Loading members...',
    'member.back': 'Back to Members',
    'member.not_found': 'Member not found',
    'member.not_found_desc': "This member doesn't exist or has been removed.",
    'member.since': 'Member since',
    'member.edit': 'Edit',
    'member.delete_btn': 'Delete User',
    'member.stat_wins': 'Lottery Wins',
    'member.stat_payments': 'Total Payments',
    'member.personal_info': 'Personal Information',
    'member.tab_deposits': 'Deposit History',
    'member.tab_groups': 'Groups',
    'member.tab_wins': 'Lottery Wins',
    'member.no_deposits': 'No deposit history yet.',
    'member.no_groups': 'Not a member of any group yet.',
    'member.no_wins': 'No lottery wins yet.',
    'member.modal_delete': 'Delete Member',
    'member.delete_warning': 'Warning: This action is irreversible. All data associated with this user will be permanently deleted, including deposit history and group memberships.',
    'member.delete_confirm_label': 'Enter your admin password to confirm',
    'member.placeholder_pwd': 'Admin password',
    'member.modal_edit': 'Edit Member',
    'member.btn_save': 'Save Changes',
    'member.success_update': 'Member updated successfully!',
    'member.loading_detail': 'Loading member details...',
  },
  am: {
    // Sidebar
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.groups': 'እቁብ ቡድኖች',
    'nav.receipts': 'ደረሰኞች',
    'nav.lottery': 'ዕጣ / እጣዎች',
    'nav.rules': 'የደንብ ቅጦች',
    'nav.notifications': 'ማሳወቂያዎች',
    'nav.settings': 'ቅንብሮች',
    'nav.logout': 'ውጣ',
    'nav.admin_panel': 'የአስተዳዳሪ ሰሌዳ',
    // Dashboard Page
    'db.title': 'ዳሽቦርድ',
    'db.subtitle': 'የእርስዎ የዲጂታል እቁብ እንቅስቃሴ አጠቃላይ እይታ',
    'db.loading': 'ዳሽቦርዱ በመጫን ላይ ነው...',
    'db.stat_groups': 'ጠቅላላ ቡድኖች',
    'db.stat_members': 'ንቁ አባላት',
    'db.stat_receipts': 'በመጠባበቅ ላይ ያሉ ደረሰኞች',
    'db.stat_collected': 'ጠቅላላ የተሰበሰበ',
    'db.chart_title': 'የተቀማጭ መጠን በጊዜ ሂደት',
    'db.chart_subtitle': 'የወርሃዊ ተቀማጭ እና የማረጋገጥ ሁኔታዎች',
    'db.chart_no_data': 'ምንም የተቀማጭ መረጃ የለም።',
    'db.chart_total': 'ጠቅላላ ተቀማጮች',
    'db.chart_verified': 'የተረጋገጡ',
    'db.activity_title': 'የቅርብ ጊዜ እንቅስቃሴዎች',
    'db.activity_view_all': 'ሁሉንም አሳይ',
    'db.activity_no_data': 'ምንም የቅርብ ጊዜ እንቅስቃሴ የለም።',
    // Settings Page
    'settings.title': 'ቅንብሮች',
    'settings.subtitle': 'የአካውንት ቅንብሮችን እና ደህንነትን ያስተዳድሩ',
    'settings.change_pwd': 'የይለፍ ቃል ቀይር',
    'settings.update_pwd_desc': 'የአስተዳዳሪ አካውንትዎን የይለፍ ቃል ያሻሽሉ',
    'settings.curr_pwd': 'የአሁኑ የይለፍ ቃል',
    'settings.new_pwd': 'አዲስ የይለፍ ቃል',
    'settings.confirm_pwd': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
    'settings.sec_note': 'እባክዎ ቢያንስ 6 ቁምፊዎች ያሉት ጠንካራ የይለፍ ቃል ይምረጡ።',
    'settings.btn_change': 'የይለፍ ቃል ቀይር',
    'settings.lang_select': 'የስርዓት ቋንቋ',
    'settings.lang_desc': 'ለዳሽቦርዱ ማሳያ የሚመርጡትን ቋንቋ ይምረጡ',
    // Groups page
    'groups.title': 'እቁብ ቡድኖች',
    'groups.subtitle': 'ሁሉንም የእቁብ ቁጠባ ቡድኖች ያስተዳድሩ',
    'groups.create_btn': 'ቡድን ፍጠር',
    'groups.search_placeholder': 'ቡድኖችን ፈልግ...',
    'groups.members': 'አባላት',
    'groups.contribution': 'መዋጮ',
    'groups.cycle': 'ዑደት',
    'groups.progress': 'ሂደት',
    'groups.no_groups': 'ምንም ቡድኖች አልተገኙም',
    'groups.no_groups_desc': 'የመጀመሪያውን የእቁብ ቡድን በመፍጠር ይጀምሩ።',
    'groups.no_groups_match': 'ከፍለጋዎ ጋር የሚዛመድ ቡድን አልተገኘም።',
    'groups.loading': 'ቡድኖች በመጫን ላይ ናቸው...',
    'groups.success_create': 'የእቁብ ቡድን በተሳካ ሁኔታ ተፈጥሯል!',
    'groups.modal_title': 'አዲስ የእቁብ ቡድን ፍጠር',
    'groups.label_name': 'የቡድን ስም',
    'groups.label_amount': 'መዋጮ (ETB)',
    'groups.label_max_members': 'ከፍተኛው የአባላት ብዛት',
    'groups.label_duration': 'የዑደት ቆይታ',
    'groups.label_description': 'መግለጫ (ከተፈለገ)',
    'groups.btn_cancel': 'ሰርዝ',
    'groups.btn_create': 'ቡድን ፍጠር',
    // Group Details page
    'group.draw_lottery': 'ዕጣ አውጣ',
    'group.back_to_groups': 'ወደ ቡድኖች ተመለስ',
    'group.not_found': 'ቡድኑ አልተገኘም',
    'group.not_found_desc': 'ይህ ቡድን የለም ወይም ለማየት ፈቃድ የለዎት።',
    'group.loading': 'የቡድኑ ዝርዝር በመጫን ላይ ነው...',
    'group.tab_deposits': 'የአሁኑ ዑደት ተቀማጮች',
    'group.tab_members': 'አባላት',
    'group.tab_rules': 'ደንቦች እና ቅንብሮች',
    'group.col_member': 'አባል',
    'group.col_amount': 'መጠን',
    'group.col_date': 'ቀን',
    'group.col_status': 'ሁኔታ',
    'group.col_actions': 'እርምጃዎች',
    'group.no_deposits': 'ለአሁኑ ዑደት ምንም የተቀማጭ ገንዘብ የለም።',
    'group.active_members': 'ንቁ አባል',
    'group.active_members_plural': 'ንቁ አባላት',
    'group.add_member': 'አባል ጨምር',
    'group.col_won': 'ያሸነፈ',
    'group.col_cycle_won': 'ያሸነፈበት ዑደት',
    'group.no_members': 'በዚህ ቡድን ውስጥ እስካሁን ምንም አባላት የሉም።',
    'group.add_first_member': 'የመጀመሪያውን አባል ጨምር',
    'group.rules_loading': 'ደንቦች በመጫን ላይ ናቸው...',
    'group.rules_title': 'የደንብ ቅጦች',
    'group.rules_subtitle': 'የተቀመጠ ደንብ ቅጥ ይጫኑ ወይም የአሁኑን ደንቦች እንደ አዲስ ቅጥ ያስቀምጡ',
    'group.save_template': 'እንደ ቅጥ አስቀምጥ',
    'group.save_changes': 'ለውጦችን አስቀምጥ',
    // Group rules settings labels
    'group.rules_deposit': 'የተቀማጭ ደንቦች',
    'group.rules_member': 'የአባልነት ደንቦች',
    'group.rules_penalty': 'የቅጣት ቅንብሮች',
    'group.rules_payout': 'የክፍያ ቅንብሮች',
    'group.rules_governance': 'አስተዳደር',
    'group.rules_additional': 'ተጨማሪ ደንቦች',
    'group.rules_save': 'ደንቦችን አስቀምጥ',
    'group.rules_unable': 'ደንቦቹን ማስጫን አልተቻለም',
    'group.next_draw': 'ቀጣይ ዕጣ',
    'group.label_require_exact': 'ትክክለኛ መጠን ያስፈልጋል',
    'group.label_require_gov_id': 'የመንግስት መታወቂያ ያስፈልጋል',
    'group.label_require_guarantor': 'ዋስ ያስፈልጋል',
    'group.label_late_penalty': 'ዘግይቶ የመክፈል ቅጣት',
    'group.label_max_skips': 'ከፍተኛ ቁጥር ዝለላዎች',
    'group.label_allow_skip': 'ዙር መዝለል ይፈቀዳል',
    'group.label_admin_fee': 'የአስተዳዳሪ ክፍያ',
    'group.label_admin_fee_type': 'የአስተዳዳሪ ክፍያ ዓይነት',
    'group.label_payout_schedule': 'የክፍያ መርሃ ግብር',
    'group.label_early_withdrawal': 'ቀደም ብሎ የማስወጣት ፖሊሲ',
    'group.label_dispute_method': 'የክርክር አፈታት ዘዴ',
    'group.label_min_members': 'ለመጀመር ዝቅተኛ አባላት',
    // Login page
    'login.title': 'እቁብ አስተዳዳሪ',
    'login.subtitle': 'ዲጂታል ቁጠባ ስርዓት',
    'login.welcome': 'እንኳን ደህና መጡ',
    'login.email': 'የኢሜይል አድራሻ',
    'login.password': 'የይለፍ ቃል',
    'login.remember': 'አስታውሰኝ',
    'login.savings': 'የቁጠባ ቡድኖች',
    'login.signin': 'ግባ',
    // Receipts extra
    'receipts.bank': 'ባንክ',
    'receipts.bank_name': 'የባንክ ስም',
    'receipts.extracted_amount': 'የተዘረዘረ መጠን',
    // Lottery extra
    'lottery.eligible': 'ብቁ',
    'lottery.col_winner': 'አሸናፊ',
    // Members extra
    'member.col_group_name': 'የቡድን ስም',
    'member.col_amount_won': 'ያሸነፉት መጠን',
    'member.save_changes': 'ለውጦችን አስቀምጥ',
    // Groups list
    'groups.frequency_weekly': 'ሳምንታዊ',
    'groups.frequency_monthly': 'ወርሃዊ',
    // Receipts page
    'receipts.title': 'ደረሰኞች',
    'receipts.subtitle_pending': 'የተቀማጭ ደረሰኞችን ያረጋግጡ',
    'receipts.filter': 'ማጣሪያ:',
    'receipts.all_status': 'ሁሉም ሁኔታ',
    'receipts.pending': 'በመጠባበቅ ላይ',
    'receipts.verified': 'የተረጋገጠ',
    'receipts.rejected': 'ውድቅ የተደረገ',
    'receipts.all_groups': 'ሁሉም ቡድኖች',
    'receipts.no_receipts': 'ምንም ደረሰኞች አልተገኙም',
    'receipts.no_receipts_desc': 'ከማጣሪያው ጋር የሚዛመድ ወይም እስካሁን የገባ ደረሰኝ የለም።',
    'receipts.modal_title': 'የደረሰኝ ዝርዝሮች',
    'receipts.ocr_title': 'በOCR የተነበበ መረጃ',
    'receipts.ocr_mismatch': '⚠️ የገንዘብ መጠን ልዩነት ተገኝቷል',
    'receipts.loading': 'ደረሰኞች በመጫን ላይ ናቸው...',
    'receipts.verify': 'አረጋግጥ',
    'receipts.reject': 'ውድቅ አድርግ',
    'receipts.ocr_ref': 'የግብይት ማጣቀሻ',
    'receipts.ocr_date': 'የተገኘበት ቀን',
    'receipts.image_label': 'የደረሰኝ ምስል',
    'receipts.no_image': 'ምስል አልተጫነም',
    'group.save_template_as': 'ደንቦችን እንደ ቴምፕሌት አስቀምጥ',
    'group.label_max_missed': 'ከፍተኛው ያለፉ ክፍያዎች',
    'group.label_max_missed_removal': 'ከመሰረዝዎ በፊት ከፍተኛው ያለፉ ክፍያዎች',
    'group.desc_skip_round': 'አባላት ዙር ማለፍ ይችላሉ',
    'group.desc_require_guarantor': 'ለመቀላቀል ዋስ መኖር አለበት',
    'group.desc_require_exact': 'ከመዋጮው ጋር ልክ መዛመድ አለበት',
    // Lottery page
    'lottery.title': 'የእቁብ ዕጣዎች',
    'lottery.subtitle': 'ለእቁብ ቡድኖች የዕጣ አወጣጥን ያስተዳድሩ እና ያከናውኑ',
    'lottery.draw_complete': '🎉 ዕጣ ማውጣት ተጠናቋል!',
    'lottery.trigger_draw': 'አዲስ ዕጣ አውጣ',
    'lottery.winner': 'አሸናፊ:',
    'lottery.gross_payout': 'ጠቅላላ አሸናፊነት:',
    'lottery.admin_fee': 'የአስተዳዳሪ ክፍያ ቅነሳ:',
    'lottery.net_payout': 'ለአባል የሚከፈል የተጣራ ክፍያ:',
    'lottery.draw_again': 'ድጋሚ ዕጣ አውጣ',
    'lottery.select_group': 'ቡድን ይምረጡ',
    'lottery.choose_group': 'ቡድን ይምረጡ...',
    'lottery.draw_now': 'አሁን ዕጣ አውጣ',
    'lottery.past_results': 'ያለፉ የዕጣ ውጤቶች',
    'lottery.past_results_desc': 'የሁሉም ቡድኖች ያለፉ ዕጣዎች ታሪክ',
    'lottery.no_results': 'እስካሁን ምንም ዕጣ አልወጣም።',
    'lottery.loading': 'ዕጣ በመጫን ላይ ነው...',
    // Notifications page
    'notifications.title': 'ማሳወቂያዎች',
    'notifications.subtitle': 'የቡድን እንቅስቃሴዎችን፣ ቀነ-ገደቦችን እና ማንቂያዎችን ይከታተሉ',
    'notifications.mark_all': 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    'notifications.loading': 'ማሳወቂያዎች በመጫን ላይ ናቸው...',
    'notifications.all_caught_up': 'ሁሉም ማሳወቂያዎች ተነበዋል!',
    'notifications.no_read': 'የተነበቡ ማሳወቂያዎች የሉም',
    'notifications.no_notifications': 'ምንም ማሳወቂያዎች የሉም',
    'notifications.no_unread_desc': 'ምንም ያልተነበበ ማሳወቂያ የለዎትም።',
    'notifications.no_read_desc': 'ያነበቧቸው ማሳወቂያዎች እዚህ ይታያሉ።',
    'notifications.no_notifications_desc': 'ስለ ቀነ-ገደቦች፣ ተቀማጮች እና ቡድን እንቅስቃሴዎች የሚመጡ ማሳወቂያዎች እዚህ ይታያሉ።',
    // Rule Templates Page
    'rules.title': 'የደንብ ቅጦች',
    'rules.subtitle': 'የደንብ ውቅሮችን በቡድኖች መካከል ያስተዳድሩ እና እንደገና ይጠቀሙ',
    'rules.create_btn': 'ቅጥ ፍጠር',
    'rules.search_placeholder': 'ቅጦችን በስም ወይም በመግለጫ ፈልግ...',
    'rules.no_templates': 'እስካሁን ምንም የደንብ ቅጦች የሉም',
    'rules.no_templates_desc': 'የደንብ ቅንብሮችን በቡድኖችዎ ውስጥ ለማስቀመጥ እና እንደገና ለመጠቀም መጀመሪያ ቅጥ ይፍጠሩ።',
    'rules.no_templates_match': 'ምንም ተዛማጅ ቅጦች አልተገኙም',
    'rules.no_templates_match_desc': 'ሌላ የፍለጋ ቃል ይሞክሩ።',
    'rules.loading': 'ቅጦች በመጫን ላይ ናቸው...',
    'rules.modal_create': 'የደንብ ቅጥ ፍጠር',
    'rules.modal_edit': 'የደንብ ቅጥ አሻሽል',
    'rules.btn_cancel': 'ሰርዝ',
    'rules.btn_create': 'ቅጥ ፍጠር',
    'rules.btn_save': 'ለውጦችን አስቀምጥ',
    'rules.label_name': 'የቅጥ ስም *',
    'rules.label_desc': 'መግለጫ',
    'rules.label_desc_placeholder': 'የዚህ ቅጥ አጭር መግለጫ...',
    // Members & Member Detail Pages
    'members.title': 'የመድረክ አባላት',
    'members.subtitle': 'ሁሉንም የመድረክ አባላት ያስተዳድሩ',
    'members.add_btn': 'አባል ጨምር',
    'members.search_placeholder': 'በስም፣ በስልክ ወይም በቴሌግራም መለያ ፈልግ...',
    'members.col_name': 'ስም',
    'members.col_phone': 'ስልክ',
    'members.col_telegram': 'ቴሌግራም',
    'members.col_groups': 'ቡድኖች',
    'members.col_deposits': 'ጠቅላላ ተቀማጭ',
    'members.col_joined': 'የተቀላቀለበት',
    'members.no_members': 'ምንም አባላት አልተገኙም',
    'members.no_members_desc': 'እስካሁን ምንም አባላት የሉም። ለመጀመር የመጀመሪያውን አባል ይጨምሩ።',
    'members.no_members_match': 'ከፍለጋዎ ጋር የሚዛመድ አባል አልተገኘም።',
    'members.modal_title': 'አዲስ አባል ጨምር',
    'members.label_name': 'ሙሉ ህጋዊ ስም *',
    'members.label_phone': 'የስልክ ቁጥር *',
    'members.label_gov_id': 'የመንግስት መታወቂያ / ዲጂታል መታወቂያ',
    'members.label_telegram': 'የቴሌግራም መለያ',
    'members.label_photo': 'ፎቶ',
    'members.label_marital': 'የጋብቻ ሁኔታ',
    'members.label_employment': 'የቅጥር ሁኔታ',
    'members.label_employer': 'የቀጣሪ / ኩባንያ ስም',
    'members.label_country': 'ሀገር',
    'members.label_city': 'ከተማ',
    'members.label_subcity': 'ክፍለ ከተማ',
    'members.label_woreda': 'ወረዳ',
    'members.label_house': 'የቤት ቁጥር',
    'members.basic_info': 'መሰረታዊ መረጃ',
    'members.personal_details': 'የግል ዝርዝሮች',
    'members.address': 'አድራሻ',
    'members.btn_cancel': 'ሰርዝ',
    'members.btn_add': 'አባል ጨምር',
    'members.success_create': 'አባል በተሳካ ሁኔታ ተጨምሯል!',
    'members.loading': 'አባላት በመጫን ላይ ናቸው...',
    'member.back': 'ወደ አባላት ተመለስ',
    'member.not_found': 'አባል አልተገኘም',
    'member.not_found_desc': 'ይህ አባል የለም ወይም ተወግዷል።',
    'member.since': 'አባል ከ',
    'member.edit': 'አስተካክል',
    'member.delete_btn': 'አባል ሰርዝ',
    'member.stat_wins': 'የዕጣ ድሎች',
    'member.stat_payments': 'ጠቅላላ ክፍያዎች',
    'member.personal_info': 'የግል መረጃ',
    'member.tab_deposits': 'የክፍያ ታሪክ',
    'member.tab_groups': 'ቡድኖች',
    'member.tab_wins': 'የዕጣ ድሎች',
    'member.no_deposits': 'እስካሁን ምንም የክፍያ ታሪክ የለም።',
    'member.no_groups': 'እስካሁን የማንኛውም ቡድን አባል አይደለም።',
    'member.no_wins': 'እስካሁን ምንም የዕጣ ድል የለም።',
    'member.modal_delete': 'አባል ሰርዝ',
    'member.delete_warning': 'ማስጠንቀቂያ፡ ይህ ድርጊት የማይመለስ ነው። የክፍያ ታሪክ እና የቡድን አባልነትን ጨምሮ ከዚህ ተጠቃሚ ጋር የተያያዙ ሁሉም መረጃዎች በቋሚነት ይጠፋሉ።',
    'member.delete_confirm_label': 'ለማረጋገጥ የአስተዳዳሪ የይለፍ ቃልዎን ያስገቡ',
    'member.placeholder_pwd': 'የአስተዳዳሪ የይለፍ ቃል',
    'member.modal_edit': 'አባል መረጃ አስተካክል',
    'member.btn_save': 'ለውጦችን አስቀምጥ',
    'member.success_update': 'የአባል መረጃ በተሳካ ሁኔታ ተሻሽሏል!',
    'member.loading_detail': 'የአባል ዝርዝር መረጃ በመጫን ላይ ነው...',
  },
  om: {
    // Sidebar
    'nav.dashboard': 'Daashboordii',
    'nav.groups': 'Garee Equb',
    'nav.receipts': 'Nagahee',
    'nav.lottery': 'Tikettii / Carraa',
    'nav.rules': 'Unka Seeraa',
    'nav.notifications': 'Beeksisa',
    'nav.settings': 'Qiyyaasota',
    'nav.logout': 'Baʼi',
    'nav.admin_panel': 'Daashboordii Admin',
    // Dashboard Page
    'db.title': 'Daashboordii',
    'db.subtitle': 'Walii-gala sochiilee equb keessanii',
    'db.loading': 'Daashboordiin feʼamaa jira...',
    'db.stat_groups': 'Waliigala Garee',
    'db.stat_members': 'Miseensota Hojii Irra Jiran',
    'db.stat_receipts': 'Nagaheewwan Eegamaa Jiran',
    'db.stat_collected': 'Waliigala Kan Sassaabame',
    'db.chart_title': 'Kaffaltii Adeemsa Yeroo Keessatti',
    'db.chart_subtitle': 'Haala kaffaltii fi mirkaneessuu jiʼaa',
    'db.chart_no_data': 'Ragaan kaffaltii hin jiru.',
    'db.chart_total': 'Kaffaltii Waliigalaa',
    'db.chart_verified': 'Mirkanaaʼe',
    'db.activity_title': 'Sochii Dhiheenya Kun',
    'db.activity_view_all': 'Hunda ilaali',
    'db.activity_no_data': 'Sochiin dhiheenya kanaa hin jiru.',
    // Settings Page
    'settings.title': 'Qiyyaasota',
    'settings.subtitle': 'Qiyyaasota herrega keessanii fi nageenya bulchaa',
    'settings.change_pwd': 'Jeedhalocha Jijjiiri',
    'settings.update_pwd_desc': 'Jeedhalocha herrega keessanii haaraa godhaa',
    'settings.curr_pwd': 'Jeedhalocha Ammaa',
    'settings.new_pwd': 'Jeedhalocha Haaraa',
    'settings.confirm_pwd': 'Jeedhalocha Haaraa Mirkaneessi',
    'settings.sec_note': 'Jeedhalocha cimaa yoo xiqqaate mallattolee 6 qabu filadhaa.',
    'settings.btn_change': 'Jeedhalocha Jijjiiri',
    'settings.lang_select': 'Afaan Sirnaa',
    'settings.lang_desc': 'Afaan daashboordiif filattan filadhaa',
    // Groups page
    'groups.title': 'Garee Equb',
    'groups.subtitle': 'Garee kaffaltii qusannoo equb hunda bulchaa',
    'groups.create_btn': 'Garee Uumi',
    'groups.search_placeholder': 'Garee barbadi...',
    'groups.members': 'Miseensota',
    'groups.contribution': 'Kaffaltii',
    'groups.cycle': 'Carraa/Cycle',
    'groups.progress': 'Haala Adeemsaa',
    'groups.no_groups': 'Gareen hin argamne',
    'groups.no_groups_desc': 'Garee equb keessan isa jalqabaa uumuun jalqabaa.',
    'groups.no_groups_match': 'Gareen barbaaddan hin argamne.',
    'groups.loading': 'Garee feʼamaa jira...',
    'groups.success_create': 'Gareen equb milkiin uumameera!',
    'groups.modal_title': 'Garee Equb Haaraa Uumi',
    'groups.label_name': 'Maqaa Garee',
    'groups.label_amount': 'Kaffaltii (ETB)',
    'groups.label_max_members': 'Miseensota Max',
    'groups.label_duration': 'Yeroo Carraa',
    'groups.label_description': 'Ibsa (Filannoo)',
    'groups.btn_cancel': 'Haqi',
    'groups.btn_create': 'Garee Uumi',
    // Group Details page
    'group.draw_lottery': 'Carraa Basi',
    'group.back_to_groups': "Gareetti Deebi'i",
    'group.not_found': 'Gareen hin argamne',
    'group.not_found_desc': 'Gareen kun hin jiru ykn ilaaluuf hayyama hin qabdu.',
    'group.loading': "Ragaa garee fe'amaa jira...",
    'group.tab_deposits': 'Kaffaltii Marsaa Ammaa',
    'group.tab_members': 'Miseensota',
    'group.tab_rules': 'Seera & Qiyyaasota',
    'group.col_member': 'Miseensa',
    'group.col_amount': 'Hamma',
    'group.col_date': 'Guyyaa',
    'group.col_status': 'Haala',
    'group.col_actions': 'Gocha',
    'group.no_deposits': 'Kaffaltiin marsaa ammaa hin jiru.',
    'group.active_members': 'Miseensa hojjataa',
    'group.active_members_plural': 'Miseensota hojjatan',
    'group.add_member': 'Miseensa Dabali',
    'group.col_won': "Kan Mo'ate",
    'group.col_cycle_won': "Marsaa Mo'ate",
    'group.no_members': 'Garee kana keessa miseensonni hin jiran.',
    'group.add_first_member': 'Miseensa Jalqabaa Dabali',
    'group.rules_loading': "Seerotni fe'amaa jiru...",
    'group.rules_title': 'Unka Seeraa',
    'group.rules_subtitle': "Unka seeraa kuusame fe'i ykn seera ammaa akka unka haaraatti kuusi",
    'group.save_template': 'Akka Unkaatti Kuusi',
    'group.save_changes': 'Jijjiirama Kuusi',
    // Group rules settings labels
    'group.rules_deposit': 'Seera Kaffaltii',
    'group.rules_member': 'Seera Miseensummaa',
    'group.rules_penalty': 'Eeyyama Adabbii',
    'group.rules_payout': "Qindaa'ina Kaffaltii",
    'group.rules_governance': 'Bulchiinsa',
    'group.rules_additional': 'Seera Dabalataa',
    'group.rules_save': 'Seera Eeggi',
    'group.rules_unable': "Seera fe'uu hin dandeenye",
    'group.next_draw': 'Caraa Itti Aanuu',
    'group.label_require_exact': 'Qabeenya Sirriiti Barbaachisaa',
    'group.label_require_gov_id': 'ID Mootummaa Barbaachisaa',
    'group.label_require_guarantor': 'Wabii Barbaachisaa',
    'group.label_late_penalty': 'Adabbii Yeroo Boodaa',
    'group.label_max_skips': 'Irra Caalaa Darbuu',
    'group.label_allow_skip': 'Marsaa Darbuu Hayyamuu',
    'group.label_admin_fee': 'Kaffaltii Admin',
    'group.label_admin_fee_type': 'Gosa Kaffaltii Admin',
    'group.label_payout_schedule': 'Karoora Kaffaltii',
    'group.label_early_withdrawal': "Seeraa Ba'uu Dura",
    'group.label_dispute_method': 'Mala Falmii Furuu',
    'group.label_min_members': "Miseensa Murtaa'aa Jalqabuuf",
    // Login page
    'login.title': 'Equb Admin',
    'login.subtitle': 'Platform Qusannaa Diijitaalaa',
    'login.welcome': 'Baga Nagaan Deebittan',
    'login.email': 'Teessoo Imeelii',
    'login.password': 'Jecha Darbii',
    'login.remember': 'Na Yaadadhu',
    'login.savings': 'Gareelee Qusannaa',
    'login.signin': 'Seeni',
    // Receipts extra
    'receipts.bank': 'Baankii',
    'receipts.bank_name': 'Maqaa Baankii',
    'receipts.extracted_amount': "Baay'ee Baasuun",
    // Lottery extra
    'lottery.eligible': "Ga'ee",
    'lottery.col_winner': "Mo'ataa",
    // Members extra
    'member.col_group_name': 'Maqaa Garee',
    'member.col_amount_won': "Baay'ee Mo'atame",
    'member.save_changes': 'Jijjiirama Eeggi',
    // Groups list
    'groups.frequency_weekly': 'Torban torban',
    'groups.frequency_monthly': "Ji'a ji'a",
    // Receipts page
    'receipts.title': 'Nagahee',
    'receipts.subtitle_pending': 'Nagaheewwan mirkaneessi',
    'receipts.filter': 'Gingilchaa:',
    'receipts.all_status': 'Haala Hunda',
    'receipts.pending': 'Eeggamaa',
    'receipts.verified': "Mirkanaa'e",
    'receipts.rejected': 'Kufaa',
    'receipts.all_groups': 'Garee Hunda',
    'receipts.no_receipts': 'Nagaheen hin argamne',
    'receipts.no_receipts_desc': 'Nagaheen gingilchaa wajjin wal simu hin argamne.',
    'receipts.modal_title': 'Ragaa Nagahee',
    'receipts.ocr_title': "Ragaa OCR n Dubbisame",
    'receipts.ocr_mismatch': '⚠️ Garaagarummaa hamma kaffaltii argameera',
    'receipts.loading': "Nagaheen fe'amaa jira...",
    'receipts.verify': 'Mirkaneessi',
    'receipts.reject': 'Kufi',
    'receipts.ocr_ref': 'Transaction Ref',
    'receipts.ocr_date': 'Guyyaa OCR n Dubbisame',
    'receipts.image_label': 'Fakkii Nagahee',
    'receipts.no_image': 'Fakkiin hin fe-amne',
    'group.save_template_as': 'Akka Unkaatti Kuusi',
    'group.label_max_missed': 'Kaffaltii Dhabame Ol-aanaa',
    'group.label_max_missed_removal': 'Haqamuu dura kaffaltii dhabame ol-aanaa',
    'group.desc_skip_round': "Miseensonni marsaa bira darbuu danda'u",
    'group.desc_require_guarantor': "Miseensa ta'uuf wabii qabaachuu qaba",
    'group.desc_require_exact': "Kaffaltii waliin tokko ta'uu qaba",
    // Lottery page
    'lottery.title': 'Carraawwan Equb',
    'lottery.subtitle': 'Carraa equb bulchaa fi baasaa',
    'lottery.draw_complete': '🎉 Baasiin Carraa Xumurameera!',
    'lottery.trigger_draw': 'Carraa Haaraa Baasi',
    'lottery.winner': "Mo'ataa:",
    'lottery.gross_payout': "Kaffaltii Mo'atame:",
    'lottery.admin_fee': 'Kaffaltii Bulchiinsaa:',
    'lottery.net_payout': 'Kaffaltii Qulqulluu Miseensaa:',
    'lottery.draw_again': 'Carraa Dabalataa Baasi',
    'lottery.select_group': 'Garee Filadhu',
    'lottery.choose_group': 'Garee filadhu...',
    'lottery.draw_now': 'Amma Baasi',
    'lottery.past_results': "Bu'aa Carraa Darbe",
    'lottery.past_results_desc': 'Seenaa carraa garee hunda keessatti baafame',
    'lottery.no_results': 'Hanga ammaatti carraan hin baane.',
    'lottery.loading': "Carraan fe'amaa jira...",
    // Notifications page
    'notifications.title': 'Beeksisa',
    'notifications.subtitle': 'Sochii garee, guyyaa xumuraa fi gorsa hordofi',
    'notifications.mark_all': 'Hunda dubbisame godhi',
    'notifications.loading': "Beeksisni fe'amaa jira...",
    'notifications.all_caught_up': 'Beeksisni hundi dubbisameera!',
    'notifications.no_read': 'Beeksisni dubbisame hin jiru',
    'notifications.no_notifications': 'Beeksisni hin jiru',
    'notifications.no_unread_desc': 'Beeksisni hin dubbisamne hin jiru.',
    'notifications.no_read_desc': "Beeksisni dubbistan asitti mul'ata.",
    'notifications.no_notifications_desc': "Beeksisni guyyaa xumuraa, kaffaltii fi sochii garee asitti mul'ata.",
    // Members & Member Detail Pages
    'members.title': 'Miseensota Platform',
    'members.subtitle': 'Miseensota platform hunda bulchaa',
    'members.add_btn': 'Miseensa Dabali',
    'members.search_placeholder': 'Maqaa, bilbila ykn Telegram ID n barbaadi...',
    'members.col_name': 'Maqaa',
    'members.col_phone': 'Bilbila',
    'members.col_telegram': 'Telegram',
    'members.col_groups': 'Gareewwan',
    'members.col_deposits': 'Kaffaltii Waliigalaa',
    'members.col_joined': 'Kan Makame',
    'members.no_members': 'Miseensi hin argamne',
    'members.no_members_desc': 'Hanga ammaatti miseensi hin jiru. Jalqabuuf miseensa jalqabaa dabali.',
    'members.no_members_match': 'Miseensi barbaadame hin argamne.',
    'members.modal_title': 'Miseensa Haaraa Dabali',
    'members.label_name': 'Maqaa Guutuu Seeraa *',
    'members.label_phone': 'Lakk Bilbilaa *',
    'members.label_gov_id': 'ID Mootummaa / ID Diijitaalaa',
    'members.label_telegram': 'Telegram ID',
    'members.label_photo': 'Fakkii',
    'members.label_marital': 'Haala Gaayilaa',
    'members.label_employment': 'Gosa Hojii',
    'members.label_employer': 'Maqaa Hojjechiisaa / Dhaabbataa',
    'members.label_country': 'Biyya',
    'members.label_city': 'Magaalaa',
    'members.label_subcity': 'Kifla Magaalaa',
    'members.label_woreda': 'Woreda',
    'members.label_house': 'Lakk Manaa',
    'members.basic_info': "Oduu Bu'uuraa",
    'members.personal_details': 'Dhimma Dhuunfaa',
    'members.address': 'Teessoo',
    'members.btn_cancel': 'Dhiisi',
    'members.btn_add': 'Miseensa Dabali',
    'members.success_create': 'Miseensi milkiin dabameera!',
    'members.loading': "Miseensonni bu'aa jiru...",
    'member.back': "Gara Miseensotatti Deebi'i",
    'member.not_found': 'Miseensi hin argamne',
    'member.not_found_desc': 'Miseensi kun hin jiru ykn haqameera.',
    'member.since': 'Miseensa erga',
    'member.edit': 'Gulaali',
    'member.delete_btn': 'Fayyadamaa Haqi',
    'member.stat_wins': "Mo'achuu Carraa",
    'member.stat_payments': 'Kaffaltii Waliigalaa',
    'member.personal_info': 'Oduu Dhuunfaa',
    'member.tab_deposits': 'Seenaa Kaffaltii',
    'member.tab_groups': 'Gareewwan',
    'member.tab_wins': "Mo'achuu Carraa",
    'member.no_deposits': 'Seenaan kaffaltii hin jiru.',
    'member.no_groups': 'Garee tokkottuu hin makamne.',
    'member.no_wins': "Carraan mo'atame hin jiru.",
    'member.modal_delete': 'Miseensa Haqi',
    'member.delete_warning': "Hubachiisa: Gochi kun hin deebi'u. Ragaaleen kaffaltii fi miseensummaa garee dabalatee odeeffannoon fayyadamaa kanaa guutummaatti ni haqama.",
    'member.delete_confirm_label': 'Mirkaneessuuf password bulchaa galchi',
    'member.placeholder_pwd': 'Password bulchaa',
    'member.modal_edit': 'Miseensa Gulaali',
    'member.btn_save': 'Jijjiirama Eeggi',
    'member.success_update': 'Miseensi milkiin gulaalameera!',
    'member.loading_detail': "Odeeffannoon miseensaa bu'aa jira...",
  },
  ti: {
    // Sidebar
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.groups': 'እቁብ ጉጅለታት',
    'nav.receipts': 'ቅብሊት / ደረሰኝ',
    'nav.lottery': 'ዕጫ / ዕጫታት',
    'nav.rules': 'ንድፊ ደንብታት',
    'nav.notifications': 'መጠንቀቅታታት',
    'nav.settings': 'ቅንብራት',
    'nav.logout': 'ውጻእ',
    'nav.admin_panel': 'መእተዊ አስተዳዳሪ',
    // Dashboard Page
    'db.title': 'ዳሽቦርድ',
    'db.subtitle': 'ናይ እቁብ ንጥፈታትኩም ሓፈሻዊ ርእይቶ',
    'db.loading': 'ዳሽቦርድ ይጽዓን ኣሎ...',
    'db.stat_groups': 'ጠቕላላ ጉጅለታት',
    'db.stat_members': 'ንጡፋት ኣባላት',
    'db.stat_receipts': 'ዝጽበዩ ዘለዉ ቅብሊት',
    'db.stat_collected': 'ጠቕላላ ዝተኣከበ',
    'db.chart_title': 'ኣታዊታት ብሰንጠረዥ የርኢ',
    'db.chart_subtitle': 'ወርሃዊ ተቀማጭን ምርግጋጽን',
    'db.chart_no_data': 'ክሳብ ሕጂ ዝተመዝገበ የተቀማጭ መረዳእታ የለን።',
    'db.chart_total': 'ጠቕላላ ተቀማጦ',
    'db.chart_verified': 'ዝተረጋገጹ',
    'db.activity_title': 'ናይ ቀረባ ግዜ ንጥፈታት',
    'db.activity_view_all': 'ኹሉ ኣርኢ',
    'db.activity_no_data': 'ናይ ቀረባ ግዜ ንጥፈታት የለን።',
    // Settings Page
    'settings.title': 'ቅንብራት',
    'settings.subtitle': 'ናይ ሒሳብ ቅንብራትን ድሕንነትን ይምሓድሩ',
    'settings.change_pwd': 'መልፈኽፈኺ ቃል ቀይር',
    'settings.update_pwd_desc': 'ናይ ሒሳብኩም መተሓላለፊ ቃል የሐድሱ',
    'settings.curr_pwd': 'ናይ ሕጂ መተሓላለፊ ቃል',
    'settings.new_pwd': 'ሓድሽ መተሓላለፊ ቃል',
    'settings.confirm_pwd': 'ነቲ ሓድሽ ቃል የረጋግጹ',
    'settings.sec_note': 'እባክኹም ብውሑዱ 6 ፊደላት ዘለዎ ሓያል ቃል ይምረጹ።',
    'settings.btn_change': 'መልፈኽፈኺ ቃል ቀይር',
    'settings.lang_select': 'ናይ ስርዓት ቋንቋ',
    'settings.lang_desc': 'ንመሰረታዊ ማዕቀፍ ዝጥቀሙሉ ቋንቋ ይምረጹ',
    // Groups page
    'groups.title': 'እቁብ ጉጅለታት',
    'groups.subtitle': 'ኹሎም ናይ እቁብ ቁጠባ ጉጅለታት ይምሓድሩ',
    'groups.create_btn': 'ጉጅለ ፍጠር',
    'groups.search_placeholder': 'ጉጅለታት ድለዩ...',
    'groups.members': 'ኣባላት',
    'groups.contribution': 'መዋጮ',
    'groups.cycle': 'ዑደት',
    'groups.progress': 'ናይ ስራሕ ኹነታት',
    'groups.no_groups': 'ምንም ጉጅለታት ኣይተረኸቡን',
    'groups.no_groups_desc': 'ቀዳማይ ናይ እቁብ ጉጅለኹም ብምፍጣር ይጀምሩ።',
    'groups.no_groups_match': 'ብፍለጋኹም ዝተረኸበ ጉጅለ የለን።',
    'groups.loading': 'ጉጅለታት ይጽዓኑ ኣለዉ...',
    'groups.success_create': 'ናይ እቁብ ጉጅለ ብዓወት ተፈጢሩ ኣሎ!',
    'groups.modal_title': 'ሓድሽ ናይ እቁብ ጉጅለ ፍጠር',
    'groups.label_name': 'ስም ጉጅለ',
    'groups.label_amount': 'መዋጮ (ETB)',
    'groups.label_max_members': 'ዝለዓለ መጠን ኣባላት',
    'groups.label_duration': 'ናይ ዑደት ግዜ',
    'groups.label_description': 'መግለጺ (ኣማራጺ)',
    'groups.btn_cancel': 'ሰርዝ',
    'groups.btn_create': 'ጉጅለ ፍጠር',
    // Group Details page
    'group.draw_lottery': 'ዕጫ ኣውጽእ',
    'group.back_to_groups': 'ነበር ናብ ጉጅለታት',
    'group.not_found': 'ጉጅለ ኣይተረኸበን',
    'group.not_found_desc': 'እዚ ጉጅለ እዚ የለን ወይ ድማ ናይ ምርኣይ ፍቓድ የብልኩምን።',
    'group.loading': 'ናይ ጉጅለ ዝርዝር ይጽዓን ኣሎ...',
    'group.tab_deposits': 'ናይ ሕጂ ዑደት ኣታዊታት',
    'group.tab_members': 'ኣባላት',
    'group.tab_rules': 'ደንብታትን ቅንብራትን',
    'group.col_member': 'ኣባል',
    'group.col_amount': 'መጠን',
    'group.col_date': 'ዕለት',
    'group.col_status': 'ኹነታት',
    'group.col_actions': 'ተግባራት',
    'group.no_deposits': 'ነዚ ዑደት ዝኸውን ኣታዊታት የለን።',
    'group.active_members': 'ንጡፍ ኣባል',
    'group.active_members_plural': 'ንጡፋት ኣባላት',
    'group.add_member': 'ኣባል ወስኽ',
    'group.col_won': 'ዝዓረገ/ዝተዓወተ',
    'group.col_cycle_won': 'ዝተዓወተሉ ዑደት',
    'group.no_members': 'ኣብዚ ጉጅለ እዚ ክሳብ ሕጂ ኣባላት የለዉን።',
    'group.add_first_member': 'ቀዳማይ ኣባል ወስኽ',
    'group.rules_loading': 'ደንብታት ይጽዓኑ ኣለዉ...',
    'group.rules_title': 'ንድፊ ደንብታት',
    'group.rules_subtitle': 'ዝተዓቀበ ንድፊ ደንብታት የውርዱ ወይ እውን ነዞም ደንብታት እዚኦም ከም ሓድሽ ንድፊ ይዕቅቡ',
    'group.save_template': 'ከም ንድፊ ዕቅብ',
    'group.save_changes': 'ለውጥታት ዕቅብ',
    // Group rules settings labels
    'group.rules_deposit': 'ደንብታት ክፍሊት',
    'group.rules_member': 'ደንብታት ኣባልነት',
    'group.rules_penalty': 'ቅንብር ቅጻዓት',
    'group.rules_payout': 'ቅንብር ወጻኢ',
    'group.rules_governance': 'አስተዳድሮ',
    'group.rules_additional': 'ተወሳኺ ደንብታት',
    'group.rules_save': 'ደንብታት ዕቅብ',
    'group.rules_unable': 'ደንብታት ናይ ምጽዓን ዓቅሚ ኣይነበሮን',
    'group.next_draw': 'ዝቕጽል ዕጫ',
    'group.label_require_exact': 'ልክዕ መጠን የድሊ',
    'group.label_require_gov_id': 'መለለዪ መንግስቲ የድሊ',
    'group.label_require_guarantor': 'ዋሕስ የድሊ',
    'group.label_late_penalty': 'ቅጻዕ ናይ ምስ ዝደንጎወ ክፍሊት',
    'group.label_max_skips': 'ዝለዓለ ናይ ምዝላል ቁጽሪ',
    'group.label_allow_skip': 'ዕጫ ምዝላል ይፍቀድ',
    'group.label_admin_fee': 'ክፍሊት አስተዳዳሪ',
    'group.label_admin_fee_type': 'ዓይነት ክፍሊት አስተዳዳሪ',
    'group.label_payout_schedule': 'ቅደም ሰዓብ ናይ ክፍሊት',
    'group.label_early_withdrawal': 'ፖሊሲ ናይ ቅድሚ ግዜ ምውጻእ',
    'group.label_dispute_method': 'ኣገባብ ናይ ምፍታሕ ምኽባር',
    'group.label_min_members': 'ዝትሑት አባላት ንምጅማር',
    // Login page
    'login.title': 'Equb አስተዳዳሪ',
    'login.subtitle': 'ዲጂታል ቁጠባ ሲስተም',
    'login.welcome': 'እንቋዕ ብሰላም ተመለሱ',
    'login.email': 'ኣድራሻ ኢሜይል',
    'login.password': 'ምስጢራዊ ቃል',
    'login.remember': 'ዘክረኒ',
    'login.savings': 'ጉጅለታት ቁጠባ',
    'login.signin': 'እቶ',
    // Receipts extra
    'receipts.bank': 'ባንኪ',
    'receipts.bank_name': 'ሽም ባንኪ',
    'receipts.extracted_amount': 'ዝተዘርዘረ መጠን',
    // Lottery extra
    'lottery.eligible': 'ብቑዕ',
    'lottery.col_winner': 'ዓወታዊ',
    // Members extra
    'member.col_group_name': 'ሽም ጉጅለ',
    'member.col_amount_won': 'ዝተዓወተ መጠን',
    'member.save_changes': 'ለውጥታት ዓቅብ',
    // Groups list
    'groups.frequency_weekly': 'ናይ ሰሙን',
    'groups.frequency_monthly': 'ናይ ወርሒ',
    // Receipts page
    'receipts.title': 'ቅብሊት / ደረሰኝ',
    'receipts.subtitle_pending': 'ናይ ተቀማጦ ቅብሊት የረጋግጹ',
    'receipts.filter': 'መጻረዪ:',
    'receipts.all_status': 'ኹሉ ኹነታት',
    'receipts.pending': 'ዝጽበ',
    'receipts.verified': 'ዝተረጋገጸ',
    'receipts.rejected': 'ውድቅ ዝተገብረ',
    'receipts.all_groups': 'ኹሎም ጉጅለታት',
    'receipts.no_receipts': 'ቅብሊት ኣይተረኸበን',
    'receipts.no_receipts_desc': 'ነቲ መጻረዪ ዝሰማማዕ ቅብሊት ኣይተረኸበን።',
    'receipts.modal_title': 'ዝርዝር ቅብሊት',
    'receipts.ocr_title': 'ብOCR ዝተነበበ መረዳእታ',
    'receipts.ocr_mismatch': '⚠️ ፍልልይ መጠን ገንዘብ ተረኺቡ',
    'receipts.loading': 'ቅብሊት ይጽዓን ኣሎ...',
    'receipts.verify': 'አረጋግጽ',
    'receipts.reject': 'ውድቅ ግበር',
    'receipts.ocr_ref': 'ናይ ትራንዛክሽን መለለዪ',
    'receipts.ocr_date': 'ዝተነበበሉ ዕለት',
    'receipts.image_label': 'ምስሊ ናይ ደረሰኝ',
    'receipts.no_image': 'ምስሊ ኣይተጻዕነን',
    'group.save_template_as': 'ደንብታት ከም ቅጥዒ ዓቅብ',
    'group.label_max_missed': 'ዝለዓለና ዝተረፈ ክፍሊት',
    'group.label_max_missed_removal': 'ቅድሚ ምስራዝ ዝለዓለና ዝተረፈ ክፍሊት',
    'group.desc_skip_round': 'ኣባላት ዙር ክሓልፉ ይኽእሉ እዮም',
    'group.desc_require_guarantor': 'ንምጽንባር ውሕስና ክህልዎ ይግባእ',
    'group.desc_require_exact': 'ምስቲ ክፍሊት ልክዕ ክገጥም ኣለዎ',
    // Lottery page
    'lottery.title': 'ዕጫታት እቁብ',
    'lottery.subtitle': 'ናይ እቁብ ዕጫታት ይምሓድሩን የካይዱን',
    'lottery.draw_complete': '🎉 ዕጫ ምውጻእ ተዛዚሙ!',
    'lottery.trigger_draw': 'ሓድሽ ዕጫ ኣውጽእ',
    'lottery.winner': 'ተዓዋቲ:',
    'lottery.gross_payout': 'ጠቕላላ ዓወት:',
    'lottery.admin_fee': 'ናይ ምምሕዳር ክፍያ:',
    'lottery.net_payout': 'ንኣባል ዝወሃብ ንጹር ክፍያ:',
    'lottery.draw_again': 'ድጋሚ ዕጫ ኣውጽእ',
    'lottery.select_group': 'ጉጅለ ይምረጹ',
    'lottery.choose_group': 'ጉጅለ ይምረጹ...',
    'lottery.draw_now': 'ሕጂ ዕጫ ኣውጽእ',
    'lottery.past_results': 'ናይ ዝሓለፉ ዕጫታት ውጽኢት',
    'lottery.past_results_desc': 'ናይ ኹሎም ጉጅለታት ናይ ሓለፉ ዕጫታት ታሪክ',
    'lottery.no_results': 'ክሳብ ሕጂ ዝወጸ ዕጫ የለን።',
    'lottery.loading': 'ዕጫ ይጽዓን ኣሎ...',
    // Notifications page
    'notifications.title': 'መጠንቀቅታታት',
    'notifications.subtitle': 'ናይ ጉጅለ ንጥፈታት፣ ናይ መወዳእታ ግዜን መጠንቀቅታታትን ይከታተሉ',
    'notifications.mark_all': 'ኹሉ ዝተነበበ ግበር',
    'notifications.loading': 'መጠንቀቅታታት ይጽዓኑ ኣለዉ...',
    'notifications.all_caught_up': 'ኹሎም መጠንቀቅታታት ተነቢቦም እዮም!',
    'notifications.no_read': 'ዝተነበቡ መጠንቀቅታታት የለዉን',
    'notifications.no_notifications': 'መጠንቀቅታ የለን',
    'notifications.no_unread_desc': 'ምንም ዘይተነበበ መጠንቀቅታ የብልኩምን።',
    'notifications.no_read_desc': 'ዘንበብኩምዎም መጠንቀቅታታት ኣብዚ ክርኣዩ እዮም።',
    'notifications.no_notifications_desc': 'ብዛዕባ ናይ መወዳእታ ግዜ፣ ኣታዊታትን ናይ ጉጅለ ንጥፈታትን ዝምልከቱ መጠንቀቅታታት ኣብዚ ክርኣዩ እዮ።',
    // Rule Templates Page
    'rules.title': 'ንድፊ ደንብታት',
    'rules.subtitle': 'ናይ ደንብታት ቅጥታት ኣብ ጉጅለታት ይምሓድሩን ይጥቀሙን',
    'rules.create_btn': 'ንድፊ ፍጠር',
    'rules.search_placeholder': 'ንድፍታት ብስም ወይ መግለጺ ድለዩ...',
    'rules.no_templates': 'ክሳብ ሕጂ ምንም ናይ ደንብታት ንድፍታት የለዉን',
    'rules.no_templates_desc': 'ናይ ደንብታት ቅንብራት ኣብ ጉጅለታትኩም ንምዕቃብን ደጊምኩም ንምጥቃምን ንድፊ ፍጠሩ።',
    'rules.no_templates_match': 'ምንም ዝሰማማዕ ንድፊ ኣይተረኸበን',
    'rules.no_templates_match_desc': 'ካልእ መእተዊ ቃል ፈትኑ።',
    'rules.loading': 'ንድፍታት ይጽዓኑ ኣለዉ...',
    'rules.modal_create': 'ናይ ደንብታት ንድፊ ፍጠር',
    'rules.modal_edit': 'ናይ ደንብታት ንድፊ ኣስተኻኽል',
    'rules.btn_cancel': 'ሰርዝ',
    'rules.btn_create': 'ንድፊ ፍጠር',
    'rules.btn_save': 'ለውጥታት ዕቅብ',
    'rules.label_name': 'ስም ንድፊ *',
    'rules.label_desc': 'መግለጺ',
    'rules.label_desc_placeholder': 'ናይዚ ንድፊ እዚ ሓጺር መግለጺ...',
    // Members & Member Detail Pages
    'members.title': 'አባላት መድረኽ',
    'members.subtitle': 'ኩሎም አባላት መድረኽ የመሓድሩ',
    'members.add_btn': 'አባል ወስኽ',
    'members.search_placeholder': 'ብሽም፣ ብስልኪ ወይ ብቴሌግራም መለለዪ ድለዩ...',
    'members.col_name': 'ሽም',
    'members.col_phone': 'ስልኪ',
    'members.col_telegram': 'ቴሌግራም',
    'members.col_groups': 'ጉጅለታት',
    'members.col_deposits': 'አጠቃላይ ክፍሊት',
    'members.col_joined': 'ዝተጸንበረሉ',
    'members.no_members': 'ዝተረኸበ አባል የለን',
    'members.no_members_desc': 'ክሳብ ሕጂ ዝተመዝገበ አባል የለን። ንምጅማር ቀዳማይ አባል ይወስኹ።',
    'members.no_members_match': 'ምስ ፍለጋኹም ዝተኣሳሰር አባል ኣይተረኸበን።',
    'members.modal_title': 'ሓድሽ አባል ወስኽ',
    'members.label_name': 'ምሉእ ሕጋዊ ሽም *',
    'members.label_phone': 'ቁጽሪ ስልኪ *',
    'members.label_gov_id': 'መለለዪ መንግስቲ / ዲጂታል መለለዪ',
    'members.label_telegram': 'ናይ ቴሌግራም መለለዪ',
    'members.label_photo': 'ስእሊ',
    'members.label_marital': 'ኩነታት መውስቦ',
    'members.label_employment': 'ኩነታት ስራሕ',
    'members.label_employer': 'ሽም ወሃብ ስራሕ / ትካል',
    'members.label_country': 'ዓዲ',
    'members.label_city': 'ከተማ',
    'members.label_subcity': 'ክፍለ ከተማ',
    'members.label_woreda': 'ወረዳ',
    'members.label_house': 'ቁጽሪ ገዛ',
    'members.basic_info': 'መሰረታዊ ሓበሬታ',
    'members.personal_details': 'ናይ ውልቂ ዝርዝር',
    'members.address': 'ኣድራሻ',
    'members.btn_cancel': 'ሰርዝ',
    'members.btn_add': 'አባል ወስኽ',
    'members.success_create': 'አባል ብዓወት ተወሲኹ ኣሎ!',
    'members.loading': 'አባላት ይጽዓኑ ኣለዉ...',
    'member.back': 'ናብ አባላት ተመለስ',
    'member.not_found': 'አባል ኣይተረኸበን',
    'member.not_found_desc': 'እዚ አባል የለን ወይ ተሰሪዙ እዩ።',
    'member.since': 'አባል ካብ',
    'member.edit': 'አስተኻኽል',
    'member.delete_btn': 'ተጠቃሚ ሰርዝ',
    'member.stat_wins': 'ዓወታት ዕጫ',
    'member.stat_payments': 'አጠቃላይ ክፍሊታት',
    'member.personal_info': 'ናይ ውልቂ ሓበሬታ',
    'member.tab_deposits': 'ታሪኽ ክፍሊት',
    'member.tab_groups': 'ጉጅለታት',
    'member.tab_wins': 'ዓወታት ዕጫ',
    'member.no_deposits': 'ክሳብ ሕጂ ታሪኽ ክፍሊት የለን።',
    'member.no_groups': 'ክሳብ ሕጂ ናይ ዝኾነ ጉጅለ አባል ኣይኮነን።',
    'member.no_wins': 'ክሳብ ሕጂ ዝኾነ ዓወት ዕጫ የለን።',
    'member.modal_delete': 'ተጠቃሚ ሰርዝ',
    'member.delete_warning': 'መተሓሳሰቢ፡ እዚ ስጉምቲ እዚ ክምለስ ኣይኽእልን እዩ። ታሪኽ ክፍሊትን ኣባልነት ጉጅለን ሓዊሱ ምስዚ ተጠቃሚ ዝተኣሳሰር ኩሉ ሓበሬታ ንሓዋሩ ክጠፍእ እዩ።',
    'member.delete_confirm_label': 'ንምርግጋጽ ናይ አስተዳዳሪ ምስጢራዊ ቃል የእትዉ',
    'member.placeholder_pwd': 'ናይ አስተዳዳሪ ምስጢራዊ ቃል',
    'member.modal_edit': 'አባል አስተኻኽል',
    'member.btn_save': 'ለውጥታት ዓቅብ',
    'member.success_update': 'ሓበሬታ አባል ብዓወት ተመሓይሹ ኣሎ!',
    'member.loading_detail': 'ዝርዝር ሓበሬታ አባል ይጽዓን ኣሎ...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('equb_lang') as Language;
    if (saved && ['en', 'am', 'om', 'ti'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('equb_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
