'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'am' | 'om' | 'ti';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.groups': 'Groups',
    'nav.receipts': 'Receipts',
    'nav.lottery': 'Lottery',
    'nav.rules': 'Rule Templates',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.admin_panel': 'Admin Dashboard',
    // Dashboard Page
    'db.title': 'Dashboard',
    'db.subtitle': 'Overview of your Equb platform activity',
    'db.loading': 'Loading dashboard...',
    'db.stat_groups': 'Total Groups',
    'db.stat_members': 'Active Members',
    'db.stat_receipts': 'Pending Receipts',
    'db.stat_collected': 'Total Collected',
    'db.chart_title': 'Deposits Over Time',
    'db.chart_subtitle': 'Monthly deposit and verification trends',
    'db.chart_no_data': 'No deposit data available yet.',
    'db.chart_total': 'Total Deposits',
    'db.chart_verified': 'Verified',
    'db.activity_title': 'Recent Activity',
    'db.activity_view_all': 'View all',
    'db.activity_no_data': 'No recent activity.',
    'db.traditional_experience': 'Traditional Experience',
    'db.active_system': 'Active System',
    'db.traditional_metrics_title': 'ዕቁብ (Equb) Trust & Community Metrics',
    'db.traditional_metrics_desc': 'Traditional Ethiopian community structures digitized. High reliability indexes indicate solid group trust and minimal payment defaults.',
    'db.geez_calendar': 'Ge\'ez Calendar',
    'db.reliability_score': 'Average Reliability Score',
    'db.excellent': 'Excellent',
    'db.active_wase': 'Active Wase (ዋስትናዎች)',
    'db.guarantees_value': '12 Guarantees',
    'db.guarantees_desc': '100% Active without Default',
    'db.emergency_skips': 'Emergency Skips Requested',
    'db.requests_value': '2 Requests',
    'db.requests_desc': 'Both approved by consensus',
    'db.coffee_mode': 'Coffee Ceremony Draw Mode',
    'db.groups_value': 'Active in 4 Groups',
    'db.coffee_desc': '3D Incense & Rekebot themes enabled',
    'db.auction_equb': 'Auction Equb (የጨረታ ዕቁብ)',
    'db.disbursed_value': 'ETB 14,500 Disbursed',
    'db.bidding_desc': 'Average 8.5% bidding discount',
    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and security',
    'settings.change_pwd': 'Change Password',
    'settings.update_pwd_desc': 'Update your admin account password',
    'settings.curr_pwd': 'Current Password',
    'settings.new_pwd': 'New Password',
    'settings.confirm_pwd': 'Confirm New Password',
    'settings.sec_note': 'Choose a strong password with at least 6 characters.',
    'settings.btn_change': 'Change Password',
    'settings.lang_select': 'System Language',
    'settings.lang_desc': 'Choose your preferred language for the dashboard display',
    // Groups page
    'groups.title': 'Equb Groups',
    'groups.subtitle': 'Manage all rotating savings groups',
    'groups.create_btn': 'Create Group',
    'groups.search_placeholder': 'Search groups...',
    'groups.members': 'Members',
    'groups.contribution': 'Contribution',
    'groups.cycle': 'Cycle',
    'groups.progress': 'Progress',
    'groups.no_groups': 'No groups found',
    'groups.no_groups_desc': 'Get started by creating your first Equb group.',
    'groups.no_groups_match': 'No groups match your search.',
    'groups.loading': 'Loading groups...',
    'groups.success_create': 'Equb group created successfully!',
    'groups.modal_title': 'Create New Equb Group',
    'groups.label_name': 'Group Name',
    'groups.label_amount': 'Contribution (ETB)',
    'groups.label_max_members': 'Max Members',
    'groups.label_duration': 'Cycle Duration',
    'groups.label_description': 'Description (Optional)',
    'groups.btn_cancel': 'Cancel',
    'groups.btn_create': 'Create Group',
    // Group Details page
    'group.draw_lottery': 'Draw Lottery',
    'group.back_to_groups': 'Back to Groups',
    'group.not_found': 'Group not found',
    'group.not_found_desc': "This group doesn't exist or you don't have permission to view it.",
    'group.loading': 'Loading group details...',
    'group.tab_deposits': 'Current Cycle Deposits',
    'group.tab_members': 'Members',
    'group.tab_rules': 'Rules & Settings',
    'group.tab_penalties': 'Penalties',
    'group.tab_disputes': 'Disputes',
    'group.tab_swaps': 'Turn Swaps',
    'group.tab_guarantors': 'Wase / ዋስ (Guarantor)',
    'group.col_member': 'Member',
    'group.col_amount': 'Amount',
    'group.col_date': 'Date',
    'group.col_status': 'Status',
    'group.col_actions': 'Actions',
    'group.no_deposits': 'No deposits for the current cycle yet.',
    'group.active_members': 'active member',
    'group.active_members_plural': 'active members',
    'group.add_member': 'Add Member',
    'group.col_won': 'Won',
    'group.col_cycle_won': 'Cycle Won',
    'group.no_members': 'No members in this group yet.',
    'group.add_first_member': 'Add First Member',
    'group.rules_loading': 'Loading rules...',
    'group.rules_title': 'Rule Templates',
    'group.rules_subtitle': 'Load a saved template or save current rules as a new template',
    'group.save_template': 'Save as Template',
    'group.save_changes': 'Save Changes',
    // Group rules settings labels
    'group.rules_deposit': 'Deposit Rules',
    'group.rules_member': 'Member Rules',
    'group.rules_penalty': 'Penalty Settings',
    'group.rules_payout': 'Payout Configuration',
    'group.rules_governance': 'Governance',
    'group.rules_additional': 'Additional Rules',
    'group.rules_save': 'Save Rules',
    'group.rules_unable': 'Unable to load rules',
    'group.next_draw': 'Next Draw',
    'group.label_require_exact': 'Require Exact Amount',
    'group.label_require_gov_id': 'Require Government ID',
    'group.label_require_guarantor': 'Require Guarantor',
    'group.label_late_penalty': 'Late Payment Penalty',
    'group.label_max_skips': 'Max Skips Allowed',
    'group.label_allow_skip': 'Allow Skip Round',
    'group.label_admin_fee': 'Admin Fee',
    'group.label_admin_fee_type': 'Admin Fee Type',
    'group.label_payout_schedule': 'Payout Schedule',
    'group.label_early_withdrawal': 'Early Withdrawal Policy',
    'group.label_dispute_method': 'Dispute Resolution Method',
    'group.label_min_members': 'Min Members to Start',
    'group.label_mid_cycle_join': 'Allow Mid-Cycle Join',
    'group.desc_mid_cycle_join': 'New members can join after a cycle has started',
    'group.label_post_win': 'Post-Win Contribution Required',
    'group.desc_post_win': 'Winners must continue paying after receiving payout',
    'group.label_auto_complete': 'Auto-Complete Group',
    'group.desc_auto_complete': 'Group auto-completes when all members have won',
    'group.desc_require_exact': 'Deposits must match the contribution amount exactly',
    'group.desc_skip_round': 'Members can skip a contribution round',
    'group.desc_require_guarantor': 'Members must have a guarantor to join',
    'group.desc_require_gov_id': 'Members must provide a kebele/national ID',
    'group.label_deposit_deadline': 'Deposit Deadline (Day of Month)',
    'group.label_min_verification': 'Min Verification Time (Hours)',
    'group.label_custom_rules': 'Custom Rules & Notes',
    'group.placeholder_custom_rules': 'Enter any additional group-specific rules, agreements, or notes here...',
    'group.rules_refresh': 'Please try refreshing the page.',
    // Penalties tab
    'group.penalties_title': 'Group Penalties',
    'group.penalties_desc': 'Track and manage member penalties for late payments or rules violations.',
    'group.col_reason': 'Reason',
    'group.col_amount_etb': 'Amount (ETB)',
    'group.btn_mark_paid': 'Mark Paid',
    'group.btn_waive': 'Waive',
    'group.no_penalties': 'No penalties recorded for this group.',
    // Disputes tab
    'group.disputes_title': 'Member Disputes',
    'group.disputes_desc': 'View and resolve group disputes filed by members.',
    'group.btn_file_dispute': 'File a Dispute',
    'group.col_filed_by': 'Filed By',
    'group.col_against': 'Against',
    'group.col_type': 'Type',
    'group.col_description': 'Description',
    'group.col_resolution': 'Resolution',
    'group.btn_resolve': 'Resolve',
    'group.no_disputes': 'No disputes filed for this group.',
    // Turn Swaps tab
    'group.swaps_title': 'Turn Swap Requests',
    'group.swaps_desc': 'Manage cycle turn swaps negotiated between group members.',
    'group.btn_request_swap': 'Request Swap',
    'group.col_requester': 'Requester',
    'group.col_target_member': 'Target Member',
    'group.col_req_turn': 'Req Turn',
    'group.col_tgt_turn': 'Tgt Turn',
    'group.btn_approve': 'Approve',
    'group.btn_reject': 'Reject',
    'group.no_swaps': 'No turn swap requests recorded for this group.',
    // Guarantors (Wase) tab
    'group.wase_title': 'Wase System (ዋስ / Guarantor)',
    'group.wase_desc': 'In traditional Ethiopian Equb, a Wase (ዋስ) is a trusted co-signer who guarantees a member\'s financial obligations to the group. If the guaranteed member defaults after winning the pot, the Wase becomes responsible. A Wase must not have won the current Equb yet.',
    'group.guarantors_title': 'Active Guarantor Arrangements',
    'group.guarantors_desc': 'Manage wase (guarantor) relationships for this group.',
    'group.btn_assign_guarantor': 'Assign Wase / Guarantor',
    'group.col_guarantor': 'Guarantor (Wase)',
    'group.col_guaranteed': 'Guaranteed Member',
    'group.col_notes': 'Notes',
    'group.col_assigned_on': 'Assigned On',
    'group.status_active': 'Active',
    'group.status_called': 'Called',
    'group.status_released': 'Released',
    'group.btn_release': 'Release',
    'group.btn_call': 'Call',
    'group.no_guarantors': 'No guarantor arrangements for this group.',
    'group.no_guarantors_hint': 'Enable "Require Guarantor" in Group Rules to make this mandatory.',
    // Modals
    'group.modal_file_dispute': 'File a Dispute',
    'group.label_dispute_type': 'Dispute Type',
    'group.option_payment_issue': 'Payment Issue',
    'group.option_rule_violation': 'Rule Violation',
    'group.option_lottery_issue': 'Lottery Draw Issue',
    'group.option_other': 'Other',
    'group.label_against_member': 'Against Member (Optional)',
    'group.option_general_dispute': 'General Group Dispute',
    'group.label_description': 'Description *',
    'group.placeholder_dispute': 'Describe the issue in detail...',
    'group.btn_submit_dispute': 'Submit Dispute',
    'group.modal_resolve': 'Resolve Dispute',
    'group.label_resolution_notes': 'Resolution Notes *',
    'group.placeholder_resolution': 'Enter resolution actions or notes...',
    'group.btn_mark_resolved': 'Mark Resolved',
    'group.modal_request_swap': 'Request a Turn Swap',
    'group.swap_desc': 'Request to swap your upcoming lottery draw turn with another group member.',
    'group.label_target_member': 'Select Target Member *',
    'group.placeholder_select_member': 'Select a member...',
    'group.label_reason': 'Reason (Optional)',
    'group.placeholder_swap_reason': 'Describe why you want to swap turns...',
    'group.btn_send_request': 'Send Request',
    'group.modal_assign_guarantor': 'Assign Wase / ዋስ (Guarantor)',
    'group.wase_rule': 'Wase Rule:',
    'group.wase_rule_desc': 'The guarantor must be an active group member who has not yet won in this Equb cycle.',
    'group.label_guarantor_select': 'Guarantor (Wase) *',
    'group.placeholder_guarantor': 'Select guarantor member...',
    'group.already_won': '(Already Won)',
    'group.label_guaranteed_select': 'Member Being Guaranteed *',
    'group.placeholder_guaranteed': 'Select member to guarantee...',
    'group.label_notes': 'Notes (Optional)',
    'group.placeholder_notes': 'Any additional context or agreement notes...',
    'group.btn_assign': 'Assign Guarantor',
    'group.btn_cancel': 'Cancel',
    // Shares & Dues tab
    'group.tab_shares': 'Shares & Dues',
    'group.shares_title': 'Member Dues Breakdown',
    'group.shares_desc': 'View calculated contributions, admin fees, and total dues per member based on their share count.',
    'group.col_shares': 'Shares',
    'group.col_contribution': 'Contribution',
    'group.col_admin_fee': 'Admin Fee',
    'group.col_total_due': 'Total Due',
    'group.col_merged': 'Merged',
    'group.btn_edit_shares': 'Edit Shares',
    'group.btn_grant_waiver': 'Grant Waiver',
    'group.btn_create_merged': 'Create Merged Group',
    'group.no_dues': 'No member dues calculated yet.',
    'group.merged_title': 'Merged Member Groups (ድርሻ ማጣመር)',
    'group.merged_desc': 'Groups of 2–4 members sharing a single contribution slot.',
    'group.merged_name': 'Group Name',
    'group.merged_members_count': 'Members',
    'group.merged_shares': 'Shares',
    'group.merged_percentage': 'Share %',
    'group.btn_dissolve': 'Dissolve',
    'group.btn_add_member_merged': 'Add Member',
    'group.btn_remove_member_merged': 'Remove',
    'group.no_merged': 'No merged member groups for this group.',
    'group.no_merged_hint': 'Create a merged group to allow 2–4 members to share a single contribution slot.',
    'group.waivers_title': 'Admin Fee Waivers',
    'group.waivers_desc': 'Members currently exempted from admin fee payments.',
    'group.col_cycles_used': 'Cycles Used',
    'group.col_duration': 'Duration',
    'group.col_missed': 'Missed After Expiry',
    'group.btn_cancel_waiver': 'Cancel Waiver',
    'group.no_waivers': 'No active fee waivers for this group.',
    'group.no_waivers_hint': 'Grant a waiver to temporarily exempt a member from admin fees.',
    'group.modal_edit_shares': 'Edit Member Shares',
    'group.label_shares_count': 'Number of Shares',
    'group.modal_grant_waiver': 'Grant Admin Fee Waiver',
    'group.label_waiver_reason': 'Reason *',
    'group.label_waiver_duration': 'Duration (Cycles) *',
    'group.placeholder_waiver_reason': 'Reason for granting fee waiver...',
    'group.modal_create_merged': 'Create Merged Member Group',
    'group.label_merged_name': 'Group Name (Optional)',
    'group.label_merged_members': 'Select Members (2–4) *',
    'group.label_merged_shares': 'Total Shares',
    'group.placeholder_merged_name': 'Auto-generated from member initials if left empty',
    'group.btn_check_status': 'Check Status',
    'group.btn_enforce': 'Enforce',
    'group.btn_view_history': 'History',
    'group.history_title': 'Payment History',
    'group.no_history': 'No cycle history available yet.',
    'group.btn_edit_percentages': 'Edit %',
    'group.btn_equal_split': 'Equal Split',
    'group.btn_save_percentages': 'Save Percentages',
    'group.modal_edit_percentages': 'Edit Share Percentages',
    'group.percentages_tip': 'Set custom percentages for unequal splits. For example, one member can pay 50% while others pay 25% each.',
    // Login page
    'login.title': 'Equb Admin',
    'login.subtitle': 'Digital Savings Platform',
    'login.welcome': 'Welcome back',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.savings': 'Savings Groups',
    'login.signin': 'Sign in',
    // Receipts extra
    'receipts.bank': 'Bank',
    'receipts.bank_name': 'Bank Name',
    'receipts.extracted_amount': 'Extracted Amount',
    // Lottery extra
    'lottery.eligible': 'Eligible',
    'lottery.col_winner': 'Winner',
    // Members extra (detail page)
    'member.col_group_name': 'Group Name',
    'member.col_amount_won': 'Amount Won',
    'member.save_changes': 'Save Changes',
    // Groups list
    'groups.frequency_weekly': 'Weekly',
    'groups.frequency_monthly': 'Monthly',
    // Receipts page
    'receipts.title': 'Receipts',
    'receipts.subtitle_pending': 'Verify deposit receipts',
    'receipts.filter': 'Filter:',
    'receipts.all_status': 'All Status',
    'receipts.pending': 'Pending',
    'receipts.verified': 'Verified',
    'receipts.rejected': 'Rejected',
    'receipts.all_groups': 'All Groups',
    'receipts.no_receipts': 'No receipts found',
    'receipts.no_receipts_desc': 'No receipts match the current filters or have been submitted yet.',
    'receipts.modal_title': 'Receipt Details',
    'receipts.ocr_title': 'OCR Extracted Data',
    'receipts.ocr_mismatch': '⚠️ Amount mismatch detected',
    'receipts.loading': 'Loading receipts...',
    'receipts.verify': 'Verify',
    'receipts.reject': 'Reject',
    'receipts.ocr_ref': 'Transaction Ref',
    'receipts.ocr_date': 'Extracted Date',
    'receipts.image_label': 'Receipt Image',
    'receipts.no_image': 'No image uploaded',
    'group.save_template_as': 'Save Rules as Template',
    'group.label_max_missed': 'Max Missed Payments',
    'group.label_max_missed_removal': 'Max Missed Payments Before Removal',
    // Lottery page
    'lottery.title': 'Lottery Draws',
    'lottery.subtitle': 'Manage and trigger lottery draws for equb groups',
    'lottery.draw_complete': '🎉 Draw Complete!',
    'lottery.trigger_draw': 'Trigger New Draw',
    'lottery.winner': 'Winner:',
    'lottery.gross_payout': 'Gross Payout Won:',
    'lottery.admin_fee': 'Admin Fee Deduction:',
    'lottery.net_payout': 'Net Member Payout:',
    'lottery.draw_again': 'Draw Again',
    'lottery.select_group': 'Select Group',
    'lottery.choose_group': 'Choose a group...',
    'lottery.draw_now': 'Draw Now',
    'lottery.past_results': 'Past Draw Results',
    'lottery.past_results_desc': 'History of all lottery draws across groups',
    'lottery.no_results': 'No lottery draws yet.',
    'lottery.loading': 'Loading lottery...',
    // Notifications page
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay updated on group activity, deadlines, and alerts',
    'notifications.mark_all': 'Mark All as Read',
    'notifications.loading': 'Loading notifications...',
    'notifications.all_caught_up': 'All caught up!',
    'notifications.no_read': 'No read notifications',
    'notifications.no_notifications': 'No notifications yet',
    'notifications.no_unread_desc': 'You have no unread notifications.',
    'notifications.no_read_desc': 'Notifications you have read will appear here.',
    'notifications.no_notifications_desc': 'Notifications about deadlines, deposits, and group activity will appear here.',
    // Rule Templates Page
    'rules.title': 'Rule Templates',
    'rules.subtitle': 'Manage and reuse rule configurations across groups',
    'rules.create_btn': 'Create Template',
    'rules.search_placeholder': 'Search templates by name or description...',
    'rules.no_templates': 'No rule templates yet',
    'rules.no_templates_desc': 'Create a template to save and reuse rule configurations across your groups.',
    'rules.no_templates_match': 'No matching templates',
    'rules.no_templates_match_desc': 'Try a different search term.',
    'rules.loading': 'Loading templates...',
    'rules.modal_create': 'Create Rule Template',
    'rules.modal_edit': 'Edit Rule Template',
    'rules.btn_cancel': 'Cancel',
    'rules.btn_create': 'Create Template',
    'rules.btn_save': 'Save Changes',
    'rules.label_name': 'Template Name *',
    'rules.label_desc': 'Description',
    'rules.label_desc_placeholder': 'Brief description of this template...',
    // Members & Member Detail Pages
    'members.title': 'Platform Members',
    'members.subtitle': 'Manage all platform members',
    'members.add_btn': 'Add Member',
    'members.search_placeholder': 'Search by name, phone, or Telegram ID...',
    'members.col_name': 'Name',
    'members.col_phone': 'Phone',
    'members.col_telegram': 'Telegram',
    'members.col_groups': 'Groups',
    'members.col_deposits': 'Total Deposits',
    'members.col_joined': 'Joined',
    'members.no_members': 'No members found',
    'members.no_members_desc': 'No members yet. Add your first member to get started.',
    'members.no_members_match': 'No members found matching your search.',
    'members.modal_title': 'Add New Member',
    'members.label_name': 'Full Legal Name *',
    'members.label_phone': 'Phone Number *',
    'members.label_gov_id': 'Government ID / Digital ID',
    'members.label_telegram': 'Telegram ID',
    'members.label_photo': 'Photo',
    'members.label_marital': 'Marital Status',
    'members.label_employment': 'Employment Type',
    'members.label_employer': 'Employer / Company Name',
    'members.label_country': 'Country',
    'members.label_city': 'City',
    'members.label_subcity': 'Sub City',
    'members.label_woreda': 'Woreda',
    'members.label_house': 'House Number',
    'members.basic_info': 'Basic Information',
    'members.personal_details': 'Personal Details',
    'members.address': 'Address',
    'members.btn_cancel': 'Cancel',
    'members.btn_add': 'Add Member',
    'members.success_create': 'Member added successfully!',
    'members.loading': 'Loading members...',
    'member.back': 'Back to Members',
    'member.not_found': 'Member not found',
    'member.not_found_desc': "This member doesn't exist or has been removed.",
    'member.since': 'Member since',
    'member.edit': 'Edit',
    'member.delete_btn': 'Delete User',
    'member.stat_wins': 'Lottery Wins',
    'member.stat_payments': 'Total Payments',
    'member.personal_info': 'Personal Information',
    'member.tab_deposits': 'Deposit History',
    'member.tab_groups': 'Groups',
    'member.tab_wins': 'Lottery Wins',
    'member.no_deposits': 'No deposit history yet.',
    'member.no_groups': 'Not a member of any group yet.',
    'member.no_wins': 'No lottery wins yet.',
    'member.modal_delete': 'Delete Member',
    'member.delete_warning': 'Warning: This action is irreversible. All data associated with this user will be permanently deleted, including deposit history and group memberships.',
    'member.delete_confirm_label': 'Enter your admin password to confirm',
    'member.placeholder_pwd': 'Admin password',
    'member.modal_edit': 'Edit Member',
    'member.btn_save': 'Save Changes',
    'member.success_update': 'Member updated successfully!',
    'member.loading_detail': 'Loading member details...',
    // Shares & Group Assignment
    'groups.label_amount_per_share': 'Contribution Per Share (ETB)',
    'groups.amount_per_share_hint': 'Amount each member pays per 1 full share per cycle',
    'members.group_assignment': 'Group Assignment (Optional)',
    'members.label_select_group': 'Select Group',
    'members.label_shares': 'Share Amount',
    'members.share_quarter': 'Quarter (25%)',
    'members.share_half': 'Half (50%)',
    'members.share_three_quarter': 'Three-Quarter (75%)',
    'members.share_full': 'Full (100%)',
    'members.expected_contribution': 'Expected Contribution',
    'members.share_preview': 'This member will pay ETB {amount} per cycle',
    'member.col_shares': 'Shares',
    'member.col_expected': 'Expected/Cycle',
    'member.edit_shares': 'Edit Shares',
    'member.shares_updated': 'Shares updated successfully!',
  },
  am: {
    // Sidebar
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.groups': 'እቁብ ቡድኖች',
    'nav.receipts': 'ደረሰኞች',
    'nav.lottery': 'ዕጣ / እጣዎች',
    'nav.rules': 'የደንብ ቅጦች',
    'nav.notifications': 'ማሳወቂያዎች',
    'nav.settings': 'ቅንብሮች',
    'nav.logout': 'ውጣ',
    'nav.admin_panel': 'የአስተዳዳሪ ሰሌዳ',
    // Dashboard Page
    'db.title': 'ዳሽቦርድ',
    'db.subtitle': 'የእርስዎ የዲጂታል እቁብ እንቅስቃሴ አጠቃላይ እይታ',
    'db.loading': 'ዳሽቦርዱ በመጫን ላይ ነው...',
    'db.stat_groups': 'ጠቅላላ ቡድኖች',
    'db.stat_members': 'ንቁ አባላት',
    'db.stat_receipts': 'በመጠባበቅ ላይ ያሉ ደረሰኞች',
    'db.stat_collected': 'ጠቅላላ የተሰበሰበ',
    'db.chart_title': 'የተቀማጭ መጠን በጊዜ ሂደት',
    'db.chart_subtitle': 'የወርሃዊ ተቀማጭ እና የማረጋገጥ ሁኔታዎች',
    'db.chart_no_data': 'ምንም የተቀማጭ መረጃ የለም።',
    'db.chart_total': 'ጠቅላላ ተቀማጮች',
    'db.chart_verified': 'የተረጋገጡ',
    'db.activity_title': 'የቅርብ ጊዜ እንቅስቃሴዎች',
    'db.activity_view_all': 'ሁሉንም አሳይ',
    'db.activity_no_data': 'ምንም የቅርብ ጊዜ እንቅስቃሴ የለም።',
    'db.traditional_experience': 'ባህላዊ ተሞክሮ',
    'db.active_system': 'ገባሪ ስርዓት',
    'db.traditional_metrics_title': 'የዕቁብ እምነትና የማህበረሰብ መለኪያዎች',
    'db.traditional_metrics_desc': 'ባህላዊ የኢትዮጵያ ማህበረሰብ መዋቅሮች በዲጂታል መልኩ ተቀርፀዋል። ከፍተኛ አስተማማኝነት ደረጃዎች ጠንካራ የቡድን እምነት እና አነስተኛ የክፍያ ጉድለቶችን ያሳያሉ።',
    'db.geez_calendar': 'ግዕዝ የቀን አቆጣጠር',
    'db.reliability_score': 'አማካይ የአስተማማኝነት ውጤት',
    'db.excellent': 'በጣም ጥሩ',
    'db.active_wase': 'ንቁ ዋስትናዎች (ዋስ)',
    'db.guarantees_value': '12 ዋስትናዎች',
    'db.guarantees_desc': '100% ንቁ ያለ ምንም ጉድለት',
    'db.emergency_skips': 'የአደጋ ጊዜ ዝላይ ጥያቄዎች',
    'db.requests_value': '2 ጥያቄዎች',
    'db.requests_desc': 'ሁለቱም በስምምነት የጸደቁ',
    'db.coffee_mode': 'የቡና ሥነ-ሥርዓት ዕጣ ሁኔታ',
    'db.groups_value': 'በ 4 ቡድኖች ውስጥ ንቁ',
    'db.coffee_desc': 'የ3-ል ዕጣን እና ረከቦት ገጽታዎች ነቅተዋል',
    'db.auction_equb': 'የጨረታ ዕቁብ',
    'db.disbursed_value': 'ETB 14,500 ተከፍሏል',
    'db.bidding_desc': 'አማካይ 8.5% የጨረታ ቅናሽ',
    // Settings Page
    'settings.title': 'ቅንብሮች',
    'settings.subtitle': 'የአካውንት ቅንብሮችን እና ደህንነትን ያስተዳድሩ',
    'settings.change_pwd': 'የይለፍ ቃል ቀይር',
    'settings.update_pwd_desc': 'የአስተዳዳሪ አካውንትዎን የይለፍ ቃል ያሻሽሉ',
    'settings.curr_pwd': 'የአሁኑ የይለፍ ቃል',
    'settings.new_pwd': 'አዲስ የይለፍ ቃል',
    'settings.confirm_pwd': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
    'settings.sec_note': 'እባክዎ ቢያንስ 6 ቁምፊዎች ያሉት ጠንካራ የይለፍ ቃል ይምረጡ።',
    'settings.btn_change': 'የይለፍ ቃል ቀይር',
    'settings.lang_select': 'የስርዓት ቋንቋ',
    'settings.lang_desc': 'ለዳሽቦርዱ ማሳያ የሚመርጡትን ቋንቋ ይምረጡ',
    // Groups page
    'groups.title': 'እቁብ ቡድኖች',
    'groups.subtitle': 'ሁሉንም የእቁብ ቁጠባ ቡድኖች ያስተዳድሩ',
    'groups.create_btn': 'ቡድን ፍጠር',
    'groups.search_placeholder': 'ቡድኖችን ፈልግ...',
    'groups.members': 'አባላት',
    'groups.contribution': 'መዋጮ',
    'groups.cycle': 'ዑደት',
    'groups.progress': 'ሂደት',
    'groups.no_groups': 'ምንም ቡድኖች አልተገኙም',
    'groups.no_groups_desc': 'የመጀመሪያውን የእቁብ ቡድን በመፍጠር ይጀምሩ።',
    'groups.no_groups_match': 'ከፍለጋዎ ጋር የሚዛመድ ቡድን አልተገኘም።',
    'groups.loading': 'ቡድኖች በመጫን ላይ ናቸው...',
    'groups.success_create': 'የእቁብ ቡድን በተሳካ ሁኔታ ተፈጥሯል!',
    'groups.modal_title': 'አዲስ የእቁብ ቡድን ፍጠር',
    'groups.label_name': 'የቡድን ስም',
    'groups.label_amount': 'መዋጮ (ETB)',
    'groups.label_max_members': 'ከፍተኛው የአባላት ብዛት',
    'groups.label_duration': 'የዑደት ቆይታ',
    'groups.label_description': 'መግለጫ (ከተፈለገ)',
    'groups.btn_cancel': 'ሰርዝ',
    'groups.btn_create': 'ቡድን ፍጠር',
    // Group Details page
    'group.draw_lottery': 'ዕጣ አውጣ',
    'group.back_to_groups': 'ወደ ቡድኖች ተመለስ',
    'group.not_found': 'ቡድኑ አልተገኘም',
    'group.not_found_desc': 'ይህ ቡድን የለም ወይም ለማየት ፈቃድ የለዎት።',
    'group.loading': 'የቡድኑ ዝርዝር በመጫን ላይ ነው...',
    'group.tab_deposits': 'የአሁኑ ዑደት ተቀማጮች',
    'group.tab_members': 'አባላት',
    'group.tab_rules': 'ደንቦች እና ቅንብሮች',
    'group.tab_penalties': 'ቅጣቶች',
    'group.tab_disputes': 'ክርክሮች',
    'group.tab_swaps': 'የዙር ልውውጥ',
    'group.tab_guarantors': 'ዋስ / ዋስትናዎች',
    'group.col_member': 'አባል',
    'group.col_amount': 'መጠን',
    'group.col_date': 'ቀን',
    'group.col_status': 'ሁኔታ',
    'group.col_actions': 'እርምጃዎች',
    'group.no_deposits': 'ለአሁኑ ዑደት ምንም የተቀማጭ ገንዘብ የለም።',
    'group.active_members': 'ንቁ አባል',
    'group.active_members_plural': 'ንቁ አባላት',
    'group.add_member': 'አባል ጨምር',
    'group.col_won': 'ያሸነፈ',
    'group.col_cycle_won': 'ያሸነፈበት ዑደት',
    'group.no_members': 'በዚህ ቡድን ውስጥ እስካሁን ምንም አባላት የሉም።',
    'group.add_first_member': 'የመጀመሪያውን አባል ጨምር',
    'group.rules_loading': 'ደንቦች በመጫን ላይ ናቸው...',
    'group.rules_title': 'የደንብ ቅጦች',
    'group.rules_subtitle': 'የተቀመጠ ደንብ ቅጥ ይጫኑ ወይም የአሁኑን ደንቦች እንደ አዲስ ቅጥ ያስቀምጡ',
    'group.save_template': 'እንደ ቅጥ አስቀምጥ',
    'group.save_changes': 'ለውጦችን አስቀምጥ',
    // Group rules settings labels
    'group.rules_deposit': 'የተቀማጭ ደንቦች',
    'group.rules_member': 'የአባልነት ደንቦች',
    'group.rules_penalty': 'የቅጣት ቅንብሮች',
    'group.rules_payout': 'የክፍያ ቅንብሮች',
    'group.rules_governance': 'አስተዳደር',
    'group.rules_additional': 'ተጨማሪ ደንቦች',
    'group.rules_save': 'ደንቦችን አስቀምጥ',
    'group.rules_unable': 'ደንቦቹን ማስጫን አልተቻለም',
    'group.next_draw': 'ቀጣይ ዕጣ',
    'group.label_require_exact': 'ትክክለኛ መጠን ያስፈልጋል',
    'group.label_require_gov_id': 'የመንግስት መታወቂያ ያስፈልጋል',
    'group.label_require_guarantor': 'ዋስ ያስፈልጋል',
    'group.label_late_penalty': 'ዘግይቶ የመክፈል ቅጣት',
    'group.label_max_skips': 'ከፍተኛ ቁጥር ዝለላዎች',
    'group.label_allow_skip': 'ዙር መዝለል ይፈቀዳል',
    'group.label_admin_fee': 'የአስተዳዳሪ ክፍያ',
    'group.label_admin_fee_type': 'የአስተዳዳሪ ክፍያ ዓይነት',
    'group.label_payout_schedule': 'የክፍያ መርሃ ግብር',
    'group.label_early_withdrawal': 'ቀደም ብሎ የማስወጣት ፖሊሲ',
    'group.label_dispute_method': 'የክርክር አፈታት ዘዴ',
    'group.label_min_members': 'ለመጀመር ዝቅተኛ አባላት',
    'group.label_mid_cycle_join': 'በዑደት መካከል መቀላቀል ይፈቅዱ',
    'group.desc_mid_cycle_join': 'ዑደት ከጀመረ በኋላ አዳዲስ አባላት መቀላቀል ይችላሉ',
    'group.label_post_win': 'ከድል በኋላ መዋጮ ያስፈልጋል',
    'group.desc_post_win': 'አሸናፊዎች ክፍያ ከተቀበሉ በኋላ መክፈል መቀጠል አለባቸው',
    'group.label_auto_complete': 'ቡድኑን በራስ-ሰር ያጠናቅቁ',
    'group.desc_auto_complete': 'ሁሉም አባላት ሲያሸንፉ ቡድኑ በራስ-ሰር ይጠናቀቃል',
    'group.desc_require_exact': 'ተቀማጮች ከመዋጮ መጠን ጋር በትክክል መዛመድ አለባቸው',
    'group.desc_skip_round': 'አባላት የመዋጮ ዙር መዝለል ይችላሉ',
    'group.desc_require_guarantor': 'አባላት ለመቀላቀል ዋስ ሊኖራቸው ይገባል',
    'group.desc_require_gov_id': 'አባላት የቀበሌ/ብሔራዊ መታወቂያ ማቅረብ አለባቸው',
    'group.label_deposit_deadline': 'የተቀማጭ ገደብ (የወሩ ቀን)',
    'group.label_min_verification': 'ዝቅተኛ የማረጋገጫ ጊዜ (ሰዓታት)',
    'group.label_custom_rules': 'ብጁ ደንቦች እና ማስታወሻዎች',
    'group.placeholder_custom_rules': 'ተጨማሪ ቡድን-ተኮር ደንቦች፣ ስምምነቶች ወይም ማስታወሻዎች ያስገቡ...',
    'group.rules_refresh': 'እባክዎ ገጹን ያድሱ።',
    'group.penalties_title': 'የቡድን ቅጣቶች',
    'group.penalties_desc': 'ለዘገየ ክፍያ ወይም የደንብ ጥሰቶች የአባላት ቅጣቶችን ይከታተሉ።',
    'group.col_reason': 'ምክንያት',
    'group.col_amount_etb': 'መጠን (ብር)',
    'group.btn_mark_paid': 'የተከፈለ ምልክት',
    'group.btn_waive': 'ተወው',
    'group.no_penalties': 'ለዚህ ቡድን ምንም ቅጣት አልተመዘገበም።',
    'group.disputes_title': 'የአባላት ክርክሮች',
    'group.disputes_desc': 'በአባላት የቀረቡ የቡድን ክርክሮችን ይመልከቱ እና ይፍቱ።',
    'group.btn_file_dispute': 'ክርክር ያቅርቡ',
    'group.col_filed_by': 'ያቀረበው',
    'group.col_against': 'በ...ላይ',
    'group.col_type': 'ዓይነት',
    'group.col_description': 'መግለጫ',
    'group.col_resolution': 'ውሳኔ',
    'group.btn_resolve': 'ፍታ',
    'group.no_disputes': 'ለዚህ ቡድን ምንም ክርክር አልቀረበም።',
    'group.swaps_title': 'የዙር ልውውጥ ጥያቄዎች',
    'group.swaps_desc': 'በቡድን አባላት መካከል የተደራደሩ የዑደት ዙር ልውውጦችን ያስተዳድሩ።',
    'group.btn_request_swap': 'ልውውጥ ጠይቅ',
    'group.col_requester': 'ጠያቂ',
    'group.col_target_member': 'ዒላማ አባል',
    'group.col_req_turn': 'ጠያቂ ዙር',
    'group.col_tgt_turn': 'ዒላማ ዙር',
    'group.btn_approve': 'ፍቀድ',
    'group.btn_reject': 'ውድቅ አድርግ',
    'group.no_swaps': 'ለዚህ ቡድን ምንም የዙር ልውውጥ ጥያቄ አልተመዘገበም።',
    'group.wase_title': 'የዋስ ስርዓት (ዋስ / Guarantor)',
    'group.wase_desc': 'በባህላዊ የኢትዮጵያ ዕቁብ ውስጥ ዋስ ማለት የአባሉን የገንዘብ ግዴታዎች ለቡድኑ የሚዋስ ታማኝ ተባባሪ ፈራሚ ነው። ዋስትና የተሰጠው አባል ድስቱን ካሸነፈ በኋላ ካልከፈለ ዋስ ኃላፊ ይሆናል። ዋስ ይህን ዕቁብ ገና ያላሸነፈ መሆን አለበት።',
    'group.guarantors_title': 'ንቁ የዋስ ሥምምነቶች',
    'group.guarantors_desc': 'ለዚህ ቡድን የዋስ (ዋስትና) ግንኙነቶችን ያስተዳድሩ።',
    'group.btn_assign_guarantor': 'ዋስ ስይም',
    'group.col_guarantor': 'ዋስ',
    'group.col_guaranteed': 'ዋስትና የተሰጠው አባል',
    'group.col_notes': 'ማስታወሻዎች',
    'group.col_assigned_on': 'የተመደበበት ቀን',
    'group.status_active': 'ንቁ',
    'group.status_called': 'ተጠርቷል',
    'group.status_released': 'ተለቋል',
    'group.btn_release': 'ልቀቅ',
    'group.btn_call': 'ጥራ',
    'group.no_guarantors': 'ለዚህ ቡድን ምንም የዋስ ሥምምነት የለም።',
    'group.no_guarantors_hint': 'ይህን ግዴታ ለማድረግ በቡድን ደንቦች ውስጥ "ዋስ ያስፈልጋል" ያንቁ።',
    'group.modal_file_dispute': 'ክርክር ያቅርቡ',
    'group.label_dispute_type': 'የክርክር ዓይነት',
    'group.option_payment_issue': 'የክፍያ ችግር',
    'group.option_rule_violation': 'የደንብ ጥሰት',
    'group.option_lottery_issue': 'የዕጣ ችግር',
    'group.option_other': 'ሌላ',
    'group.label_against_member': 'በ... ላይ (አማራጭ)',
    'group.option_general_dispute': 'አጠቃላይ የቡድን ክርክር',
    'group.label_description': 'መግለጫ *',
    'group.placeholder_dispute': 'ጉዳዩን በዝርዝር ይግለጹ...',
    'group.btn_submit_dispute': 'ክርክር ያቅርቡ',
    'group.modal_resolve': 'ክርክር ፍታ',
    'group.label_resolution_notes': 'የውሳኔ ማስታወሻዎች *',
    'group.placeholder_resolution': 'የውሳኔ እርምጃዎች ወይም ማስታወሻዎች ያስገቡ...',
    'group.btn_mark_resolved': 'የተፈታ ምልክት',
    'group.modal_request_swap': 'የዙር ልውውጥ ጠይቅ',
    'group.swap_desc': 'የሚመጣውን የዕጣ ዙር ከሌላ የቡድን አባል ጋር ለመለዋወጥ ይጠይቁ።',
    'group.label_target_member': 'ዒላማ አባል ይምረጡ *',
    'group.placeholder_select_member': 'አባል ይምረጡ...',
    'group.label_reason': 'ምክንያት (አማራጭ)',
    'group.placeholder_swap_reason': 'ዙር ለመለዋወጥ ለምን እንደሚፈልጉ ይግለጹ...',
    'group.btn_send_request': 'ጥያቄ ላክ',
    'group.modal_assign_guarantor': 'ዋስ ስይም / ዋስ (Guarantor)',
    'group.wase_rule': 'የዋስ ደንብ:',
    'group.wase_rule_desc': 'ዋስ በዚህ ዕቁብ ዑደት ውስጥ ገና ያላሸነፈ ንቁ የቡድን አባል መሆን አለበት።',
    'group.label_guarantor_select': 'ዋስ *',
    'group.placeholder_guarantor': 'የዋስ አባል ይምረጡ...',
    'group.already_won': '(ቀድሞ አሸንፏል)',
    'group.label_guaranteed_select': 'ዋስትና የሚሰጠው አባል *',
    'group.placeholder_guaranteed': 'ዋስትና የሚሰጠውን አባል ይምረጡ...',
    'group.label_notes': 'ማስታወሻዎች (አማራጭ)',
    'group.placeholder_notes': 'ማንኛውም ተጨማሪ ዐውድ ወይም የስምምነት ማስታወሻዎች...',
    'group.btn_assign': 'ዋስ ስይም',
    'group.btn_cancel': 'ሰርዝ',
    // Login page
    'login.title': 'እቁብ አስተዳዳሪ',
    'login.subtitle': 'ዲጂታል ቁጠባ ስርዓት',
    'login.welcome': 'እንኳን ደህና መጡ',
    'login.email': 'የኢሜይል አድራሻ',
    'login.password': 'የይለፍ ቃል',
    'login.remember': 'አስታውሰኝ',
    'login.savings': 'የቁጠባ ቡድኖች',
    'login.signin': 'ግባ',
    // Receipts extra
    'receipts.bank': 'ባንክ',
    'receipts.bank_name': 'የባንክ ስም',
    'receipts.extracted_amount': 'የተዘረዘረ መጠን',
    // Lottery extra
    'lottery.eligible': 'ብቁ',
    'lottery.col_winner': 'አሸናፊ',
    // Members extra
    'member.col_group_name': 'የቡድን ስም',
    'member.col_amount_won': 'ያሸነፉት መጠን',
    'member.save_changes': 'ለውጦችን አስቀምጥ',
    // Groups list
    'groups.frequency_weekly': 'ሳምንታዊ',
    'groups.frequency_monthly': 'ወርሃዊ',
    // Receipts page
    'receipts.title': 'ደረሰኞች',
    'receipts.subtitle_pending': 'የተቀማጭ ደረሰኞችን ያረጋግጡ',
    'receipts.filter': 'ማጣሪያ:',
    'receipts.all_status': 'ሁሉም ሁኔታ',
    'receipts.pending': 'በመጠባበቅ ላይ',
    'receipts.verified': 'የተረጋገጠ',
    'receipts.rejected': 'ውድቅ የተደረገ',
    'receipts.all_groups': 'ሁሉም ቡድኖች',
    'receipts.no_receipts': 'ምንም ደረሰኞች አልተገኙም',
    'receipts.no_receipts_desc': 'ከማጣሪያው ጋር የሚዛመድ ወይም እስካሁን የገባ ደረሰኝ የለም።',
    'receipts.modal_title': 'የደረሰኝ ዝርዝሮች',
    'receipts.ocr_title': 'በOCR የተነበበ መረጃ',
    'receipts.ocr_mismatch': '⚠️ የገንዘብ መጠን ልዩነት ተገኝቷል',
    'receipts.loading': 'ደረሰኞች በመጫን ላይ ናቸው...',
    'receipts.verify': 'አረጋግጥ',
    'receipts.reject': 'ውድቅ አድርግ',
    'receipts.ocr_ref': 'የግብይት ማጣቀሻ',
    'receipts.ocr_date': 'የተገኘበት ቀን',
    'receipts.image_label': 'የደረሰኝ ምስል',
    'receipts.no_image': 'ምስል አልተጫነም',
    'group.save_template_as': 'ደንቦችን እንደ ቴምፕሌት አስቀምጥ',
    'group.label_max_missed': 'ከፍተኛው ያለፉ ክፍያዎች',
    'group.label_max_missed_removal': 'ከመሰረዝዎ በፊት ከፍተኛው ያለፉ ክፍያዎች',
    // Lottery page
    'lottery.title': 'የእቁብ ዕጣዎች',
    'lottery.subtitle': 'ለእቁብ ቡድኖች የዕጣ አወጣጥን ያስተዳድሩ እና ያከናውኑ',
    'lottery.draw_complete': '🎉 ዕጣ ማውጣት ተጠናቋል!',
    'lottery.trigger_draw': 'አዲስ ዕጣ አውጣ',
    'lottery.winner': 'አሸናፊ:',
    'lottery.gross_payout': 'ጠቅላላ አሸናፊነት:',
    'lottery.admin_fee': 'የአስተዳዳሪ ክፍያ ቅነሳ:',
    'lottery.net_payout': 'ለአባል የሚከፈል የተጣራ ክፍያ:',
    'lottery.draw_again': 'ድጋሚ ዕጣ አውጣ',
    'lottery.select_group': 'ቡድን ይምረጡ',
    'lottery.choose_group': 'ቡድን ይምረጡ...',
    'lottery.draw_now': 'አሁን ዕጣ አውጣ',
    'lottery.past_results': 'ያለፉ የዕጣ ውጤቶች',
    'lottery.past_results_desc': 'የሁሉም ቡድኖች ያለፉ ዕጣዎች ታሪክ',
    'lottery.no_results': 'እስካሁን ምንም ዕጣ አልወጣም።',
    'lottery.loading': 'ዕጣ በመጫን ላይ ነው...',
    // Notifications page
    'notifications.title': 'ማሳወቂያዎች',
    'notifications.subtitle': 'የቡድን እንቅስቃሴዎችን፣ ቀነ-ገደቦችን እና ማንቂያዎችን ይከታተሉ',
    'notifications.mark_all': 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    'notifications.loading': 'ማሳወቂያዎች በመጫን ላይ ናቸው...',
    'notifications.all_caught_up': 'ሁሉም ማሳወቂያዎች ተነበዋል!',
    'notifications.no_read': 'የተነበቡ ማሳወቂያዎች የሉም',
    'notifications.no_notifications': 'ምንም ማሳወቂያዎች የሉም',
    'notifications.no_unread_desc': 'ምንም ያልተነበበ ማሳወቂያ የለዎትም።',
    'notifications.no_read_desc': 'ያነበቧቸው ማሳወቂያዎች እዚህ ይታያሉ።',
    'notifications.no_notifications_desc': 'ስለ ቀነ-ገደቦች፣ ተቀማጮች እና ቡድን እንቅስቃሴዎች የሚመጡ ማሳወቂያዎች እዚህ ይታያሉ።',
    // Rule Templates Page
    'rules.title': 'የደንብ ቅጦች',
    'rules.subtitle': 'የደንብ ውቅሮችን በቡድኖች መካከል ያስተዳድሩ እና እንደገና ይጠቀሙ',
    'rules.create_btn': 'ቅጥ ፍጠር',
    'rules.search_placeholder': 'ቅጦችን በስም ወይም በመግለጫ ፈልግ...',
    'rules.no_templates': 'እስካሁን ምንም የደንብ ቅጦች የሉም',
    'rules.no_templates_desc': 'የደንብ ቅንብሮችን በቡድኖችዎ ውስጥ ለማስቀመጥ እና እንደገና ለመጠቀም መጀመሪያ ቅጥ ይፍጠሩ።',
    'rules.no_templates_match': 'ምንም ተዛማጅ ቅጦች አልተገኙም',
    'rules.no_templates_match_desc': 'ሌላ የፍለጋ ቃል ይሞክሩ።',
    'rules.loading': 'ቅጦች በመጫን ላይ ናቸው...',
    'rules.modal_create': 'የደንብ ቅጥ ፍጠር',
    'rules.modal_edit': 'የደንብ ቅጥ አሻሽል',
    'rules.btn_cancel': 'ሰርዝ',
    'rules.btn_create': 'ቅጥ ፍጠር',
    'rules.btn_save': 'ለውጦችን አስቀምጥ',
    'rules.label_name': 'የቅጥ ስም *',
    'rules.label_desc': 'መግለጫ',
    'rules.label_desc_placeholder': 'የዚህ ቅጥ አጭር መግለጫ...',
    // Members & Member Detail Pages
    'members.title': 'የመድረክ አባላት',
    'members.subtitle': 'ሁሉንም የመድረክ አባላት ያስተዳድሩ',
    'members.add_btn': 'አባል ጨምር',
    'members.search_placeholder': 'በስም፣ በስልክ ወይም በቴሌግራም መለያ ፈልግ...',
    'members.col_name': 'ስም',
    'members.col_phone': 'ስልክ',
    'members.col_telegram': 'ቴሌግራም',
    'members.col_groups': 'ቡድኖች',
    'members.col_deposits': 'ጠቅላላ ተቀማጭ',
    'members.col_joined': 'የተቀላቀለበት',
    'members.no_members': 'ምንም አባላት አልተገኙም',
    'members.no_members_desc': 'እስካሁን ምንም አባላት የሉም። ለመጀመር የመጀመሪያውን አባል ይጨምሩ።',
    'members.no_members_match': 'ከፍለጋዎ ጋር የሚዛመድ አባል አልተገኘም።',
    'members.modal_title': 'አዲስ አባል ጨምር',
    'members.label_name': 'ሙሉ ህጋዊ ስም *',
    'members.label_phone': 'የስልክ ቁጥር *',
    'members.label_gov_id': 'የመንግስት መታወቂያ / ዲጂታል መታወቂያ',
    'members.label_telegram': 'የቴሌግራም መለያ',
    'members.label_photo': 'ፎቶ',
    'members.label_marital': 'የጋብቻ ሁኔታ',
    'members.label_employment': 'የቅጥር ሁኔታ',
    'members.label_employer': 'የቀጣሪ / ኩባንያ ስም',
    'members.label_country': 'ሀገር',
    'members.label_city': 'ከተማ',
    'members.label_subcity': 'ክፍለ ከተማ',
    'members.label_woreda': 'ወረዳ',
    'members.label_house': 'የቤት ቁጥር',
    'members.basic_info': 'መሰረታዊ መረጃ',
    'members.personal_details': 'የግል ዝርዝሮች',
    'members.address': 'አድራሻ',
    'members.btn_cancel': 'ሰርዝ',
    'members.btn_add': 'አባል ጨምር',
    'members.success_create': 'አባል በተሳካ ሁኔታ ተጨምሯል!',
    'members.loading': 'አባላት በመጫን ላይ ናቸው...',
    'member.back': 'ወደ አባላት ተመለስ',
    'member.not_found': 'አባል አልተገኘም',
    'member.not_found_desc': 'ይህ አባል የለም ወይም ተወግዷል።',
    'member.since': 'አባል ከ',
    'member.edit': 'አስተካክል',
    'member.delete_btn': 'አባል ሰርዝ',
    'member.stat_wins': 'የዕጣ ድሎች',
    'member.stat_payments': 'ጠቅላላ ክፍያዎች',
    'member.personal_info': 'የግል መረጃ',
    'member.tab_deposits': 'የክፍያ ታሪክ',
    'member.tab_groups': 'ቡድኖች',
    'member.tab_wins': 'የዕጣ ድሎች',
    'member.no_deposits': 'እስካሁን ምንም የክፍያ ታሪክ የለም።',
    'member.no_groups': 'እስካሁን የማንኛውም ቡድን አባል አይደለም።',
    'member.no_wins': 'እስካሁን ምንም የዕጣ ድል የለም።',
    'member.modal_delete': 'አባል ሰርዝ',
    'member.delete_warning': 'ማስጠንቀቂያ፡ ይህ ድርጊት የማይመለስ ነው። የክፍያ ታሪክ እና የቡድን አባልነትን ጨምሮ ከዚህ ተጠቃሚ ጋር የተያያዙ ሁሉም መረጃዎች በቋሚነት ይጠፋሉ።',
    'member.delete_confirm_label': 'ለማረጋገጥ የአስተዳዳሪ የይለፍ ቃልዎን ያስገቡ',
    'member.placeholder_pwd': 'የአስተዳዳሪ የይለፍ ቃል',
    'member.modal_edit': 'አባል መረጃ አስተካክል',
    'member.btn_save': 'ለውጦችን አስቀምጥ',
    'member.success_update': 'የአባል መረጃ በተሳካ ሁኔታ ተሻሽሏል!',
    'member.loading_detail': 'የአባል ዝርዝር መረጃ በመጫን ላይ ነው...',
    // Shares & Group Assignment
    'groups.label_amount_per_share': 'የአንድ ድርሻ አስተዋፅኦ (ETB)',
    'groups.amount_per_share_hint': 'እያንዳንዱ አባል በአንድ ሙሉ ድርሻ በየዙሩ የሚከፍለው መጠን',
    'members.group_assignment': 'የቡድን ምደባ (አማራጭ)',
    'members.label_select_group': 'ቡድን ይምረጡ',
    'members.label_shares': 'የድርሻ መጠን',
    'members.share_quarter': 'ሩብ (25%)',
    'members.share_half': 'ግማሽ (50%)',
    'members.share_three_quarter': 'ሶስት አራተኛ (75%)',
    'members.share_full': 'ሙሉ (100%)',
    'members.expected_contribution': 'የሚጠበቅ አስተዋፅኦ',
    'members.share_preview': 'ይህ አባል በየዙሩ ETB {amount} ይከፍላል',
    'member.col_shares': 'ድርሻዎች',
    'member.col_expected': 'በየዙሩ የሚጠበቅ',
    'member.edit_shares': 'ድርሻ ያስተካክሉ',
    'member.shares_updated': 'ድርሻ በተሳካ ሁኔታ ተዘምኗል!',
  },
  om: {
    // Sidebar
    'nav.dashboard': 'Daashboordii',
    'nav.groups': 'Garee Equb',
    'nav.receipts': 'Nagahee',
    'nav.lottery': 'Tikettii / Carraa',
    'nav.rules': 'Unka Seeraa',
    'nav.notifications': 'Beeksisa',
    'nav.settings': 'Qiyyaasota',
    'nav.logout': 'Baʼi',
    'nav.admin_panel': 'Daashboordii Admin',
    // Dashboard Page
    'db.title': 'Daashboordii',
    'db.subtitle': 'Walii-gala sochiilee equb keessanii',
    'db.loading': 'Daashboordiin feʼamaa jira...',
    'db.stat_groups': 'Waliigala Garee',
    'db.stat_members': 'Miseensota Hojii Irra Jiran',
    'db.stat_receipts': 'Nagaheewwan Eegamaa Jiran',
    'db.stat_collected': 'Waliigala Kan Sassaabame',
    'db.chart_title': 'Kaffaltii Adeemsa Yeroo Keessatti',
    'db.chart_subtitle': 'Haala kaffaltii fi mirkaneessuu jiʼaa',
    'db.chart_no_data': 'Ragaan kaffaltii hin jiru.',
    'db.chart_total': 'Kaffaltii Waliigalaa',
    'db.chart_verified': 'Mirkanaaʼe',
    'db.activity_title': 'Sochii Dhiheenya Kun',
    'db.activity_view_all': 'Hunda ilaali',
    'db.activity_no_data': 'Sochiin dhiheenya kanaa hin jiru.',
    'db.traditional_experience': 'Muuxannoo Aadaa',
    'db.active_system': 'Sirna Hojjataa',
    'db.traditional_metrics_title': 'Safartuu Amantaa & Hawaasa Equb',
    'db.traditional_metrics_desc': 'Caasaaleen hawaasa Itoophiyaa aadaa diijitaalawaa taʼaniiru. Safartuun amanamummaa ol-aanaan garee keessatti amantaa cimaa fi kaffaltii dhabuu xiqqaachuu agarsiisa.',
    'db.geez_calendar': 'Kalandara Gi\'izii',
    'db.reliability_score': 'Giddu-galeessa Qabxii Amanamummaa',
    'db.excellent': 'Baay\'ee Gaarii',
    'db.active_wase': 'Wabiilee Hojii Irra Jiran (Wase)',
    'db.guarantees_value': 'Wabii 12',
    'db.guarantees_desc': '100% Default malee kan hojjatu',
    'db.emergency_skips': 'Marsaa Tasaa Darbuu',
    'db.requests_value': 'Gaaffii 2',
    'db.requests_desc': 'Lachuu waliigalteedhaan mirkanaa\'aniiru',
    'db.coffee_mode': 'Haala Carraa Bunaa',
    'db.groups_value': 'Garee 4 keessatti hojjata',
    'db.coffee_desc': 'Dizayinii Aadaa Bunaa fi Qayyaa',
    'db.auction_equb': 'Equb Caalbaasii (የጨረታ ዕቁብ)',
    'db.disbursed_value': 'ETB 14,500 Kaffalameera',
    'db.bidding_desc': 'Giddu-galeessa 8.5% hirʼisa caalbaasii',
    // Settings Page
    'settings.title': 'Qiyyaasota',
    'settings.subtitle': 'Qiyyaasota herrega keessanii fi nageenya bulchaa',
    'settings.change_pwd': 'Jeedhalocha Jijjiiri',
    'settings.update_pwd_desc': 'Jeedhalocha herrega keessanii haaraa godhaa',
    'settings.curr_pwd': 'Jeedhalocha Ammaa',
    'settings.new_pwd': 'Jeedhalocha Haaraa',
    'settings.confirm_pwd': 'Jeedhalocha Haaraa Mirkaneessi',
    'settings.sec_note': 'Jeedhalocha cimaa yoo xiqqaate mallattolee 6 qabu filadhaa.',
    'settings.btn_change': 'Jeedhalocha Jijjiiri',
    'settings.lang_select': 'Afaan Sirnaa',
    'settings.lang_desc': 'Afaan daashboordiif filattan filadhaa',
    // Groups page
    'groups.title': 'Garee Equb',
    'groups.subtitle': 'Garee kaffaltii qusannoo equb hunda bulchaa',
    'groups.create_btn': 'Garee Uumi',
    'groups.search_placeholder': 'Garee barbadi...',
    'groups.members': 'Miseensota',
    'groups.contribution': 'Kaffaltii',
    'groups.cycle': 'Carraa/Cycle',
    'groups.progress': 'Haala Adeemsaa',
    'groups.no_groups': 'Gareen hin argamne',
    'groups.no_groups_desc': 'Garee equb keessan isa jalqabaa uumuun jalqabaa.',
    'groups.no_groups_match': 'Gareen barbaaddan hin argamne.',
    'groups.loading': 'Garee feʼamaa jira...',
    'groups.success_create': 'Gareen equb milkiin uumameera!',
    'groups.modal_title': 'Garee Equb Haaraa Uumi',
    'groups.label_name': 'Maqaa Garee',
    'groups.label_amount': 'Kaffaltii (ETB)',
    'groups.label_max_members': 'Miseensota Max',
    'groups.label_duration': 'Yeroo Carraa',
    'groups.label_description': 'Ibsa (Filannoo)',
    'groups.btn_cancel': 'Haqi',
    'groups.btn_create': 'Garee Uumi',
    // Group Details page
    'group.draw_lottery': 'Carraa Basi',
    'group.back_to_groups': "Gareetti Deebi'i",
    'group.not_found': 'Gareen hin argamne',
    'group.not_found_desc': 'Gareen kun hin jiru ykn ilaaluuf hayyama hin qabdu.',
    'group.loading': "Ragaa garee fe'amaa jira...",
    'group.tab_deposits': 'Kaffaltii Marsaa Ammaa',
    'group.tab_members': 'Miseensota',
    'group.tab_rules': 'Seera & Qiyyaasota',
    'group.tab_penalties': 'Adabbii',
    'group.tab_disputes': 'Falmii',
    'group.tab_swaps': 'Jijjiirraa Marsaa',
    'group.tab_guarantors': 'Wabii / Wase',
    'group.col_member': 'Miseensa',
    'group.col_amount': 'Hamma',
    'group.col_date': 'Guyyaa',
    'group.col_status': 'Haala',
    'group.col_actions': 'Gocha',
    'group.no_deposits': 'Kaffaltiin marsaa ammaa hin jiru.',
    'group.active_members': 'Miseensa hojjataa',
    'group.active_members_plural': 'Miseensota hojjatan',
    'group.add_member': 'Miseensa Dabali',
    'group.col_won': "Kan Mo'ate",
    'group.col_cycle_won': "Marsaa Mo'ate",
    'group.no_members': 'Garee kana keessa miseensonni hin jiran.',
    'group.add_first_member': 'Miseensa Jalqabaa Dabali',
    'group.rules_loading': "Seerotni fe'amaa jiru...",
    'group.rules_title': 'Unka Seeraa',
    'group.rules_subtitle': "Unka seeraa kuusame fe'i ykn seera ammaa akka unka haaraatti kuusi",
    'group.save_template': 'Akka Unkaatti Kuusi',
    'group.save_changes': 'Jijjiirama Kuusi',
    // Group rules settings labels
    'group.rules_deposit': 'Seera Kaffaltii',
    'group.rules_member': 'Seera Miseensummaa',
    'group.rules_penalty': 'Eeyyama Adabbii',
    'group.rules_payout': "Qindaa'ina Kaffaltii",
    'group.rules_governance': 'Bulchiinsa',
    'group.rules_additional': 'Seera Dabalataa',
    'group.rules_save': 'Seera Eeggi',
    'group.rules_unable': "Seera fe'uu hin dandeenye",
    'group.next_draw': 'Caraa Itti Aanuu',
    'group.label_require_exact': 'Qabeenya Sirriiti Barbaachisaa',
    'group.label_require_gov_id': 'ID Mootummaa Barbaachisaa',
    'group.label_require_guarantor': 'Wabii Barbaachisaa',
    'group.label_late_penalty': 'Adabbii Yeroo Boodaa',
    'group.label_max_skips': 'Irra Caalaa Darbuu',
    'group.label_allow_skip': 'Marsaa Darbuu Hayyamuu',
    'group.label_admin_fee': 'Kaffaltii Admin',
    'group.label_admin_fee_type': 'Gosa Kaffaltii Admin',
    'group.label_payout_schedule': 'Karoora Kaffaltii',
    'group.label_early_withdrawal': "Seeraa Ba'uu Dura",
    'group.label_dispute_method': 'Mala Falmii Furuu',
    'group.label_min_members': "Miseensa Murtaa'aa Jalqabuuf",
    'group.label_mid_cycle_join': 'Marsaa Gidduutti Makamuu Hayyami',
    'group.desc_mid_cycle_join': 'Miseensonni haaraan marsaan erga jalqabee booda makamuu danda\'u',
    'group.label_post_win': 'Mo\'achuu Booda Kaffaltiin Barbaachisaadha',
    'group.desc_post_win': 'Mo\'attoonni kaffaltii erga fudhatanii boodas kaffaluu itti fufuuf dirqama qabu',
    'group.label_auto_complete': 'Garee Ofiin Xumuri',
    'group.desc_auto_complete': 'Gareen yommuu miseensonni hundi mo\'atan ofiin xumurama',
    'group.desc_require_exact': 'Kaffaltii hamma buusichaa waliin sirriitti wal simuu qaba',
    'group.desc_skip_round': 'Miseensonni marsaa buusii tokko bira darbuu danda\'u',
    'group.desc_require_guarantor': 'Miseensonni makamuuf wabii (wase) qabaachuu qabu',
    'group.desc_require_gov_id': 'Miseensonni ID gandaa/biyoolessaa dhiheessuu qabu',
    'group.label_deposit_deadline': 'Guyyaa Dhuma Kaffaltii (Guyyaa Ji\'aa)',
    'group.label_min_verification': 'Yeroo Mirkaneessaa Xiqqaataa (Sa\'aatii)',
    'group.label_custom_rules': 'Seera Dhuunfaa & Yaadannoo',
    'group.placeholder_custom_rules': 'Seera dabalataa garee kanaa, waliigaltee ykn yaadannoo asitti galchaa...',
    'group.rules_refresh': 'Maaloo fuula kana deebisaa fe\'aa.',
    // Penalties tab
    'group.penalties_title': 'Adabbii Garee',
    'group.penalties_desc': 'Adabbii miseensotaa kaffaltii dorigoomuu ykn seera cabsuuf hordofaa fi bulchaa.',
    'group.col_reason': 'Sababa',
    'group.col_amount_etb': 'Hamma (ETB)',
    'group.btn_mark_paid': 'Kaffalame Godhi',
    'group.btn_waive': 'Dhiisi',
    'group.no_penalties': 'Adabbiin garee kanaaf galmaa\'e hin jiru.',
    // Disputes tab
    'group.disputes_title': 'Falmii Miseensotaa',
    'group.disputes_desc': 'Falmii miseensotatti dhiyaatan ilaalaa fi furaa.',
    'group.btn_file_dispute': 'Falmii Dhiheessi',
    'group.col_filed_by': 'Kan Dhiheesse',
    'group.col_against': 'Kan Irratti',
    'group.col_type': 'Gosa',
    'group.col_description': 'Ibsa',
    'group.col_resolution': 'Furmaata',
    'group.btn_resolve': 'Furi',
    'group.no_disputes': 'Falmiin garee kanaaf dhiyaate hin jiru.',
    // Turn Swaps tab
    'group.swaps_title': 'Gaaffii Jijjiirraa Marsaa',
    'group.swaps_desc': 'Jijjiirraa marsaa miseensota gidduutti taasifamu bulchaa.',
    'group.btn_request_swap': 'Jijjiirraa Gaafadhu',
    'group.col_requester': 'Gaafataa',
    'group.col_target_member': 'Miseensa Target',
    'group.col_req_turn': 'Marsaa Gaafatame',
    'group.col_tgt_turn': 'Marsaa Target',
    'group.btn_approve': 'Mirkaneessi',
    'group.btn_reject': 'Kufi',
    'group.no_swaps': 'Gaaffiin jijjiirraa marsaa garee kanaaf galmaa\'e hin jiru.',
    // Guarantors (Wase) tab
    'group.wase_title': 'Sirna Wase (ዋስ / Wabii)',
    'group.wase_desc': 'Equb aadaa Itoophiyaa keessatti, Wase (ዋስ) nama amanamaa ta\'ee kaffaltii miseensa tokkoo gareef wabii ta\'udha. Yoo miseensi wabii ta\'ameef kaffaltii dhabe, Waseen sun itti gaafatamaa ta\'a. Waseen equb ammaa kana kan hin mo\'anne ta\'uu qaba.',
    'group.guarantors_title': 'Waliigaltee Wabii Hojii Irra Jiru',
    'group.guarantors_desc': 'Garee kanaaf walitti dhufeenya wabii (wase) bulchaa.',
    'group.btn_assign_guarantor': 'Wabii (Wase) Ramadi',
    'group.col_guarantor': 'Wabii (Wase)',
    'group.col_guaranteed': 'Miseensa Wabii Ta\'ameef',
    'group.col_notes': 'Yaadannoo',
    'group.col_assigned_on': 'Guyyaa Ramadame',
    'group.status_active': 'Nutufe',
    'group.status_called': 'Waamame',
    'group.status_released': 'Gadhifame',
    'group.btn_release': 'Gadhiisi',
    'group.btn_call': 'Waami',
    'group.no_guarantors': 'Waliigalteen wabii garee kanaaf hin jiru.',
    'group.no_guarantors_hint': 'Dirqama gochuuf seera garee keessatti "Wabii Barbaachisaa" banuun danda\'ama.',
    // Modals
    'group.modal_file_dispute': 'Falmii Dhiheessi',
    'group.label_dispute_type': 'Gosa Falmii',
    'group.option_payment_issue': 'Dhimma Kaffaltii',
    'group.option_rule_violation': 'Cabsuu Seeraa',
    'group.option_lottery_issue': 'Dhimma Carraa Buusuu',
    'group.option_other': 'Kan biroo',
    'group.label_against_member': 'Miseensa Irratti (Filannoo)',
    'group.option_general_dispute': 'Falmii Waliigalaa Garee',
    'group.label_description': 'Ibsa *',
    'group.placeholder_dispute': 'Dhimma kana bal\'inaan ibsaa...',
    'group.btn_submit_dispute': 'Falmii Dhiheessi',
    'group.modal_resolve': 'Falmii Furi',
    'group.label_resolution_notes': 'Yaadannoo Furmaataa *',
    'group.placeholder_resolution': 'Tarkaanfii furmaataa ykn yaadannoo galchaa...',
    'group.btn_mark_resolved': 'Furameera Godhi',
    'group.modal_request_swap': 'Jijjiirraa Marsaa Gaafadhu',
    'group.swap_desc': 'Marsaa carraa keessan isa dhufu miseensa biraa waliin jijjiiruuf gaafadhaa.',
    'group.label_target_member': 'Miseensa Filadhu *',
    'group.placeholder_select_member': 'Miseensa filadhu...',
    'group.label_reason': 'Sababa (Filannoo)',
    'group.placeholder_swap_reason': 'Maaliif jijjiiruu akka barbaaddan ibsaa...',
    'group.btn_send_request': 'Gaaffii Ergi',
    'group.modal_assign_guarantor': 'Wabii/Wase Ramadi',
    'group.wase_rule': 'Seera Wase:',
    'group.wase_rule_desc': 'Wabiin miseensa garee kan equb ammaa kana hin mo\'atin ta\'uu qaba.',
    'group.label_guarantor_select': 'Wabii (Wase) *',
    'group.placeholder_guarantor': 'Miseensa wabii filadhu...',
    'group.already_won': '(Duraan Mo\'ateera)',
    'group.label_guaranteed_select': 'Miseensa Wabii Ta\'ameef *',
    'group.placeholder_guaranteed': 'Miseensa wabii ta\'amuufii qabu filadhu...',
    'group.label_notes': 'Yaadannoo (Filannoo)',
    'group.placeholder_notes': 'Yaadannoo ykn waliigaltee dabalataa asitti galchaa...',
    'group.btn_assign': 'Wabii Ramadi',
    'group.btn_cancel': 'Haqi',
    // Login page
    'login.title': 'Equb Admin',
    'login.subtitle': 'Platform Qusannaa Diijitaalaa',
    'login.welcome': 'Baga Nagaan Deebittan',
    'login.email': 'Teessoo Imeelii',
    'login.password': 'Jecha Darbii',
    'login.remember': 'Na Yaadadhu',
    'login.savings': 'Gareelee Qusannaa',
    'login.signin': 'Seeni',
    // Receipts extra
    'receipts.bank': 'Baankii',
    'receipts.bank_name': 'Maqaa Baankii',
    'receipts.extracted_amount': "Baay'ee Baasuun",
    // Lottery extra
    'lottery.eligible': "Ga'ee",
    'lottery.col_winner': "Mo'ataa",
    // Members extra
    'member.col_group_name': 'Maqaa Garee',
    'member.col_amount_won': "Baay'ee Mo'atame",
    'member.save_changes': 'Jijjiirama Eeggi',
    // Groups list
    'groups.frequency_weekly': 'Torban torban',
    'groups.frequency_monthly': "Ji'a ji'a",
    // Receipts page
    'receipts.title': 'Nagahee',
    'receipts.subtitle_pending': 'Nagaheewwan mirkaneessi',
    'receipts.filter': 'Gingilchaa:',
    'receipts.all_status': 'Haala Hunda',
    'receipts.pending': 'Eeggamaa',
    'receipts.verified': "Mirkanaa'e",
    'receipts.rejected': 'Kufaa',
    'receipts.all_groups': 'Garee Hunda',
    'receipts.no_receipts': 'Nagaheen hin argamne',
    'receipts.no_receipts_desc': 'Nagaheen gingilchaa wajjin wal simu hin argamne.',
    'receipts.modal_title': 'Ragaa Nagahee',
    'receipts.ocr_title': "Ragaa OCR n Dubbisame",
    'receipts.ocr_mismatch': '⚠️ Garaagarummaa hamma kaffaltii argameera',
    'receipts.loading': "Nagaheen fe'amaa jira...",
    'receipts.verify': 'Mirkaneessi',
    'receipts.reject': 'Kufi',
    'receipts.ocr_ref': 'Transaction Ref',
    'receipts.ocr_date': 'Guyyaa OCR n Dubbisame',
    'receipts.image_label': 'Fakkii Nagahee',
    'receipts.no_image': 'Fakkiin hin fe-amne',
    'group.save_template_as': 'Akka Unkaatti Kuusi',
    'group.label_max_missed': 'Kaffaltii Dhabame Ol-aanaa',
    'group.label_max_missed_removal': 'Haqamuu dura kaffaltii dhabame ol-aanaa',
    // Lottery page
    'lottery.title': 'Carraawwan Equb',
    'lottery.subtitle': 'Carraa equb bulchaa fi baasaa',
    'lottery.draw_complete': '🎉 Baasiin Carraa Xumurameera!',
    'lottery.trigger_draw': 'Carraa Haaraa Baasi',
    'lottery.winner': "Mo'ataa:",
    'lottery.gross_payout': "Kaffaltii Mo'atame:",
    'lottery.admin_fee': 'Kaffaltii Bulchiinsaa:',
    'lottery.net_payout': 'Kaffaltii Qulqulluu Miseensaa:',
    'lottery.draw_again': 'Carraa Dabalataa Baasi',
    'lottery.select_group': 'Garee Filadhu',
    'lottery.choose_group': 'Garee filadhu...',
    'lottery.draw_now': 'Amma Baasi',
    'lottery.past_results': "Bu'aa Carraa Darbe",
    'lottery.past_results_desc': 'Seenaa carraa garee hunda keessatti baafame',
    'lottery.no_results': 'Hanga ammaatti carraan hin baane.',
    'lottery.loading': "Carraan fe'amaa jira...",
    // Notifications page
    'notifications.title': 'Beeksisa',
    'notifications.subtitle': 'Sochii garee, guyyaa xumuraa fi gorsa hordofi',
    'notifications.mark_all': 'Hunda dubbisame godhi',
    'notifications.loading': "Beeksisni fe'amaa jira...",
    'notifications.all_caught_up': 'Beeksisni hundi dubbisameera!',
    'notifications.no_read': 'Beeksisni dubbisame hin jiru',
    'notifications.no_notifications': 'Beeksisni hin jiru',
    'notifications.no_unread_desc': 'Beeksisni hin dubbisamne hin jiru.',
    'notifications.no_read_desc': "Beeksisni dubbistan asitti mul'ata.",
    'notifications.no_notifications_desc': "Beeksisni guyyaa xumuraa, kaffaltii fi sochii garee asitti mul'ata.",
    // Members & Member Detail Pages
    'members.title': 'Miseensota Platform',
    'members.subtitle': 'Miseensota platform hunda bulchaa',
    'members.add_btn': 'Miseensa Dabali',
    'members.search_placeholder': 'Maqaa, bilbila ykn Telegram ID n barbaadi...',
    'members.col_name': 'Maqaa',
    'members.col_phone': 'Bilbila',
    'members.col_telegram': 'Telegram',
    'members.col_groups': 'Gareewwan',
    'members.col_deposits': 'Kaffaltii Waliigalaa',
    'members.col_joined': 'Kan Makame',
    'members.no_members': 'Miseensi hin argamne',
    'members.no_members_desc': 'Hanga ammaatti miseensi hin jiru. Jalqabuuf miseensa jalqabaa dabali.',
    'members.no_members_match': 'Miseensi barbaadame hin argamne.',
    'members.modal_title': 'Miseensa Haaraa Dabali',
    'members.label_name': 'Maqaa Guutuu Seeraa *',
    'members.label_phone': 'Lakk Bilbilaa *',
    'members.label_gov_id': 'ID Mootummaa / ID Diijitaalaa',
    'members.label_telegram': 'Telegram ID',
    'members.label_photo': 'Fakkii',
    'members.label_marital': 'Haala Gaayilaa',
    'members.label_employment': 'Gosa Hojii',
    'members.label_employer': 'Maqaa Hojjechiisaa / Dhaabbataa',
    'members.label_country': 'Biyya',
    'members.label_city': 'Magaalaa',
    'members.label_subcity': 'Kifla Magaalaa',
    'members.label_woreda': 'Woreda',
    'members.label_house': 'Lakk Manaa',
    'members.basic_info': "Oduu Bu'uuraa",
    'members.personal_details': 'Dhimma Dhuunfaa',
    'members.address': 'Teessoo',
    'members.btn_cancel': 'Dhiisi',
    'members.btn_add': 'Miseensa Dabali',
    'members.success_create': 'Miseensi milkiin dabameera!',
    'members.loading': "Miseensonni bu'aa jiru...",
    'member.back': "Gara Miseensotatti Deebi'i",
    'member.not_found': 'Miseensi hin argamne',
    'member.not_found_desc': 'Miseensi kun hin jiru ykn haqameera.',
    'member.since': 'Miseensa erga',
    'member.edit': 'Gulaali',
    'member.delete_btn': 'Fayyadamaa Haqi',
    'member.stat_wins': "Mo'achuu Carraa",
    'member.stat_payments': 'Kaffaltii Waliigalaa',
    'member.personal_info': 'Oduu Dhuunfaa',
    'member.tab_deposits': 'Seenaa Kaffaltii',
    'member.tab_groups': 'Gareewwan',
    'member.tab_wins': "Mo'achuu Carraa",
    'member.no_deposits': 'Seenaan kaffaltii hin jiru.',
    'member.no_groups': 'Garee tokkottuu hin makamne.',
    'member.no_wins': "Carraan mo'atame hin jiru.",
    'member.modal_delete': 'Miseensa Haqi',
    'member.delete_warning': "Hubachiisa: Gochi kun hin deebi'u. Ragaaleen kaffaltii fi miseensummaa garee dabalatee odeeffannoon fayyadamaa kanaa guutummaatti ni haqama.",
    'member.delete_confirm_label': 'Mirkaneessuuf password bulchaa galchi',
    'member.placeholder_pwd': 'Password bulchaa',
    'member.modal_edit': 'Miseensa Gulaali',
    'member.btn_save': 'Jijjiirama Eeggi',
    'member.success_update': 'Miseensi milkiin gulaalameera!',
    'member.loading_detail': "Odeeffannoon miseensaa bu'aa jira...",
    // Shares & Group Assignment
    'groups.label_amount_per_share': 'Buusii Gahee Tokkoo (ETB)',
    'groups.amount_per_share_hint': 'Hanga miseensi tokko gahee guutuu tokkoof marsaa tokkotti kaffalu',
    'members.group_assignment': 'Ramaddii Garee (Dirqama Miti)',
    'members.label_select_group': 'Garee Filadhu',
    'members.label_shares': 'Hanga Gahee',
    'members.share_quarter': 'Kurmaana (25%)',
    'members.share_half': 'Walakka (50%)',
    'members.share_three_quarter': 'Harka Sadi (75%)',
    'members.share_full': 'Guutuu (100%)',
    'members.expected_contribution': 'Buusii Eegamu',
    'members.share_preview': 'Miseensi kun marsaa tokkotti ETB {amount} kaffala',
    'member.col_shares': 'Gaheewwan',
    'member.col_expected': 'Marsaatti Eegamu',
    'member.edit_shares': 'Gahee Gulaali',
    'member.shares_updated': 'Gaheen milkiin haaromfameera!',
  },
  ti: {
    // Sidebar
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.groups': 'እቁብ ጉጅለታት',
    'nav.receipts': 'ቅብሊት / ደረሰኝ',
    'nav.lottery': 'ዕጫ / ዕጫታት',
    'nav.rules': 'ንድፊ ደንብታት',
    'nav.notifications': 'መጠንቀቅታታት',
    'nav.settings': 'ቅንብራት',
    'nav.logout': 'ውጻእ',
    'nav.admin_panel': 'መእተዊ አስተዳዳሪ',
    // Dashboard Page
    'db.title': 'ዳሽቦርድ',
    'db.subtitle': 'ናይ እቁብ ንጥፈታትኩም ሓፈሻዊ ርእይቶ',
    'db.loading': 'ዳሽቦርድ ይጽዓን ኣሎ...',
    'db.stat_groups': 'ጠቕላላ ጉጅለታት',
    'db.stat_members': 'ንጡፋት ኣባላት',
    'db.stat_receipts': 'ዝጽበዩ ዘለዉ ቅብሊት',
    'db.stat_collected': 'ጠቕላላ ዝተኣከበ',
    'db.chart_title': 'ኣታዊታት ብሰንጠረዥ የርኢ',
    'db.chart_subtitle': 'ወርሃዊ ተቀማጭን ምርግጋጽን',
    'db.chart_no_data': 'ክሳብ ሕጂ ዝተመዝገበ የተቀማጭ መረዳእታ የለን።',
    'db.chart_total': 'ጠቕላላ ተቀማጦ',
    'db.chart_verified': 'ዝተረጋገጹ',
    'db.activity_title': 'ናይ ቀረባ ግዜ ንጥፈታት',
    'db.activity_view_all': 'ኹሉ ኣርኢ',
    'db.activity_no_data': 'ናይ ቀረባ ግዜ ንጥፈታት የለን።',
    'db.traditional_experience': 'ልምዲ ባህሊ',
    'db.active_system': 'ንጡፍ ስርዓት',
    'db.traditional_metrics_title': 'መለክዒታት እምነትን ማሕበረሰብን እቁብ',
    'db.traditional_metrics_desc': 'ባህላዊ ማሕበረሰባዊ መዋቕራት ኢትዮጵያ ብዲጂታል መልክዕ ተዳልዮም ኣለዉ። ልዑል መዐቀኒ እምነት ጽኑዕ ናይ ሓባር ምትእምማንን ውሑድ ዘይምኽፋል ክፍሊትን የርኢ።',
    'db.geez_calendar': 'ግእዝ ዓውደ-ኣዋርሕ',
    'db.reliability_score': 'ማእከላይ መዐቀኒ እምነት',
    'db.excellent': 'ጣዕሚ ጽቡቕ',
    'db.active_wase': 'ንጡፋት ዋሕስ (ዋስትና)',
    'db.guarantees_value': '12 ዋስትናታት',
    'db.guarantees_desc': '100% ንጡፍ ብዘይ ዝኾነ ሕጽረት',
    'db.emergency_skips': 'ናይ ህጹጽ ግዜ ምዝላል ሕቶታት',
    'db.requests_value': '2 ሕቶታት',
    'db.requests_desc': 'ኽልቲኦም ብስምምዕ ዝጸደቑ',
    'db.coffee_mode': 'ስነ-ስርዓት ቡን ዕጫ',
    'db.groups_value': 'ኣብ 4 ጉጅለታት ንጡፍ',
    'db.coffee_desc': 'ናይ 3D ዕጣንን ረከቦትን ገጽታታት ተኸፊቶም ኣለዉ',
    'db.auction_equb': 'ናይ ጨረታ እቁብ',
    'db.disbursed_value': 'ETB 14,500 ተኸፊሉ',
    'db.bidding_desc': 'ማእከላይ 8.5% ናይ ጨረታ ቅናሽ',
    // Settings Page
    'settings.title': 'ቅንብራት',
    'settings.subtitle': 'ናይ ሒሳብ ቅንብራትን ድሕንነትን ይምሓድሩ',
    'settings.change_pwd': 'መልፈኽፈኺ ቃል ቀይር',
    'settings.update_pwd_desc': 'ናይ ሒሳብኩም መተሓላለፊ ቃል የሐድሱ',
    'settings.curr_pwd': 'ናይ ሕጂ መተሓላለፊ ቃል',
    'settings.new_pwd': 'ሓድሽ መተሓላለፊ ቃል',
    'settings.confirm_pwd': 'ነቲ ሓድሽ ቃል የረጋግጹ',
    'settings.sec_note': 'እባክኹም ብውሑዱ 6 ፊደላት ዘለዎ ሓያል ቃል ይምረጹ።',
    'settings.btn_change': 'መልፈኽፈኺ ቃል ቀይር',
    'settings.lang_select': 'ናይ ስርዓት ቋንቋ',
    'settings.lang_desc': 'ንመሰረታዊ ማዕቀፍ ዝጥቀሙሉ ቋንቋ ይምረጹ',
    // Groups page
    'groups.title': 'እቁብ ጉጅለታት',
    'groups.subtitle': 'ኹሎም ናይ እቁብ ቁጠባ ጉጅለታት ይምሓድሩ',
    'groups.create_btn': 'ጉጅለ ፍጠር',
    'groups.search_placeholder': 'ጉጅለታት ድለዩ...',
    'groups.members': 'ኣባላት',
    'groups.contribution': 'መዋጮ',
    'groups.cycle': 'ዑደት',
    'groups.progress': 'ናይ ስራሕ ኹነታት',
    'groups.no_groups': 'ምንም ጉጅለታት ኣይተረኸቡን',
    'groups.no_groups_desc': 'ቀዳማይ ናይ እቁብ ጉጅለኹም ብምፍጣር ይጀምሩ።',
    'groups.no_groups_match': 'ብፍለጋኹም ዝተረኸበ ጉጅለ የለን።',
    'groups.loading': 'ጉጅለታት ይጽዓኑ ኣለዉ...',
    'groups.success_create': 'ናይ እቁብ ጉጅለ ብዓወት ተፈጢሩ ኣሎ!',
    'groups.modal_title': 'ሓድሽ ናይ እቁብ ጉጅለ ፍጠር',
    'groups.label_name': 'ስም ጉጅለ',
    'groups.label_amount': 'መዋጮ (ETB)',
    'groups.label_max_members': 'ዝለዓለ መጠን ኣባላት',
    'groups.label_duration': 'ናይ ዑደት ግዜ',
    'groups.label_description': 'መግለጺ (ኣማራጺ)',
    'groups.btn_cancel': 'ሰርዝ',
    'groups.btn_create': 'ጉጅለ ፍጠር',
    // Group Details page
    'group.draw_lottery': 'ዕጫ ኣውጽእ',
    'group.back_to_groups': 'ነበር ናብ ጉጅለታት',
    'group.not_found': 'ጉጅለ ኣይተረኸበን',
    'group.not_found_desc': 'እዚ ጉጅለ እዚ የለን ወይ ድማ ናይ ምርኣይ ፍቓድ የብልኩምን።',
    'group.loading': 'ናይ ጉጅለ ዝርዝር ይጽዓን ኣሎ...',
    'group.tab_deposits': 'ናይ ሕጂ ዑደት ኣታዊታት',
    'group.tab_members': 'ኣባላት',
    'group.tab_rules': 'ደንብታትን ቅንብራትን',
    'group.tab_penalties': 'ቅጻዓት',
    'group.tab_disputes': 'ክትዓት / ምስሕሓብ',
    'group.tab_swaps': 'ናይ ዑደት ልውውጥ',
    'group.tab_guarantors': 'ዋሕስ / ዋስትና',
    'group.col_member': 'ኣባል',
    'group.col_amount': 'መጠን',
    'group.col_date': 'ዕለት',
    'group.col_status': 'ኹነታት',
    'group.col_actions': 'ተግባራት',
    'group.no_deposits': 'ነዚ ዑደት ዝኸውን ኣታዊታት የለን።',
    'group.active_members': 'ንጡፍ ኣባል',
    'group.active_members_plural': 'ንጡፋት ኣባላት',
    'group.add_member': 'ኣባል ወስኽ',
    'group.col_won': 'ዝዓረገ/ዝተዓወተ',
    'group.col_cycle_won': 'ዝተዓወተሉ ዑደት',
    'group.no_members': 'ኣብዚ ጉጅለ እዚ ክሳብ ሕጂ ኣባላት የለዉን።',
    'group.add_first_member': 'ቀዳማይ ኣባል ወስኽ',
    'group.rules_loading': 'ደንብታት ይጽዓኑ ኣለዉ...',
    'group.rules_title': 'ንድፊ ደንብታት',
    'group.rules_subtitle': 'ዝተዓቀበ ንድፊ ደንብታት የውርዱ ወይ እውን ነዞም ደንብታት እዚኦም ከም ሓድሽ ንድፊ ይዕቅቡ',
    'group.save_template': 'ከም ንድፊ ዕቅብ',
    'group.save_changes': 'ለውጥታት ዕቅብ',
    // Group rules settings labels
    'group.rules_deposit': 'ደንብታት ክፍሊት',
    'group.rules_member': 'ደንብታት ኣባልነት',
    'group.rules_penalty': 'ቅንብር ቅጻዓት',
    'group.rules_payout': 'ቅንብር ወጻኢ',
    'group.rules_governance': 'አስተዳድሮ',
    'group.rules_additional': 'ተወሳኺ ደንብታት',
    'group.rules_save': 'ደንብታት ዕቅብ',
    'group.rules_unable': 'ደንብታት ናይ ምጽዓን ዓቅሚ ኣይነበሮን',
    'group.next_draw': 'ዝቕጽል ዕጫ',
    'group.label_require_exact': 'ልክዕ መጠን የድሊ',
    'group.label_require_gov_id': 'መለለዪ መንግስቲ የድሊ',
    'group.label_require_guarantor': 'ዋሕስ የድሊ',
    'group.label_late_penalty': 'ቅጻዕ ናይ ምስ ዝደንጎወ ክፍሊት',
    'group.label_max_skips': 'ዝለዓለ ናይ ምዝላል ቁጽሪ',
    'group.label_allow_skip': 'ዕጫ ምዝላል ይፍቀድ',
    'group.label_admin_fee': 'ክፍሊት አስተዳዳሪ',
    'group.label_admin_fee_type': 'ዓይነት ክፍሊት አስተዳዳሪ',
    'group.label_payout_schedule': 'ቅደም ሰዓብ ናይ ክፍሊት',
    'group.label_early_withdrawal': 'ፖሊሲ ናይ ቅድሚ ግዜ ምውጻእ',
    'group.label_dispute_method': 'ኣገባብ ናይ ምፍታሕ ምኽባር',
    'group.label_min_members': 'ዝትሑት አባላት ንምጅማር',
    'group.label_mid_cycle_join': 'ኣብ ማእኸል ዑደት ምጽንባር ይፍቀድ',
    'group.desc_mid_cycle_join': 'ዑደት ድሕሪ ምጅማሩ ሓደስቲ ኣባላት ክጽንበሩ ይኽእሉ እዮም',
    'group.label_post_win': 'ድሕሪ ዓወት መዋጮ የድሊ',
    'group.desc_post_win': 'ተዓወትቲ ድሕሪ ክፍሊት ምርካቦም ምኽፋል ክቕጽሉ ኣለዎም',
    'group.label_auto_complete': 'ነቲ ጉጅለ ብኣውቶማቲክ ወድእ',
    'group.desc_auto_complete': 'ኹሎም ኣባላት ምስ ተዓወቱ እቲ ጉጅለ ብኣውቶማቲክ ይጠናቀቕ',
    'group.desc_require_exact': 'ኣታዊታት ምስቲ ክፍሊት ልክዕ ክገጥም ኣለዎ',
    'group.desc_skip_round': 'ኣባላት ዙር ክፍሊት ክሓልፉ ይኽእሉ እዮም',
    'group.desc_require_guarantor': 'ኣባላት ንምጽንባር ዋሕስ (ዋስ) ክህልዎም ይግባእ',
    'group.desc_require_gov_id': 'ኣባላት ናይ ቀበሌ/ሃገራዊ መለለዪ ወረቐት ከቕርቡ ኣለዎም',
    'group.label_deposit_deadline': 'ናይ መወዳእታ መዓልቲ ክፍሊት (መዓልቲ ወርሒ)',
    'group.label_min_verification': 'ዝተሓተ ናይ ምርግጋጽ ግዜ (ሰዓታት)',
    'group.label_custom_rules': 'ባዕላዊ ደንብታትን ማስታወሻታትን',
    'group.placeholder_custom_rules': 'ዝኾነ ተወሳኺ ጉጅለ-ተኮር ደንብታት፣ ስምምዓት ወይ ማስታወሻታት ኣብዚ የእትዉ...',
    'group.rules_refresh': 'በጃኹም ነቲ ገጽ እንደገና ጽዓንዎ።',
    // Penalties tab
    'group.penalties_title': 'ቅጻዓት ጉጅለ',
    'group.penalties_desc': 'ንዝደንጎዩ ክፍሊታት ወይ ምግሃስ ደንብታት ዝምልከቱ ናይ ኣባላት ቅጻዓት ተኸታተሉን ይምሓድሩን።',
    'group.col_reason': 'ምኽንያት',
    'group.col_amount_etb': 'መጠን (ETB)',
    'group.btn_mark_paid': 'ዝተኸፈለ ይገበር',
    'group.btn_waive': 'ሕደገሉ',
    'group.no_penalties': 'ነዚ ጉጅለ ዝተመዝገበ ቅጻዕ የለን።',
    // Disputes tab
    'group.disputes_title': 'ምስሕሓብ ኣባላት',
    'group.disputes_desc': 'ብኣባላት ዝቐረቡ ናይ ጉጅለ ምስሕሓባት ርኣዩን ፍትሑን።',
    'group.btn_file_dispute': 'ምስሕሓብ ኣቕርብ',
    'group.col_filed_by': 'ዝኣቀረበ',
    'group.col_against': 'ኣንጻር',
    'group.col_type': 'ዓይነት',
    'group.col_description': 'መግለጺ',
    'group.col_resolution': 'ፍታሕ',
    'group.btn_resolve': 'ፍታሕ',
    'group.no_disputes': 'ነዚ ጉጅለ ዝቐረበ ምስሕሓብ የለን።',
    // Turn Swaps tab
    'group.swaps_title': 'ሕቶታት ልውውጥ ዑደት',
    'group.swaps_desc': 'ኣብ መንጎ ኣባላት ጉጅለ ዝተገብሩ ናይ ዑደት ልውውጥ ሕቶታት ይምሓድሩ።',
    'group.btn_request_swap': 'ልውውጥ ሕተት',
    'group.col_requester': 'ሓታቲ',
    'group.col_target_member': 'ዒላማ ኣባል',
    'group.col_req_turn': 'ዝተሓተተ ዑደት',
    'group.col_tgt_turn': 'ዒላማ ዑደት',
    'group.btn_approve': 'ኣጽድቕ',
    'group.btn_reject': 'ውድቅ ግበር',
    'group.no_swaps': 'ነዚ ጉጅለ ዝተመዝገበ ናይ ዑደት ልውውጥ ሕቶ የለን።',
    // Guarantors (Wase) tab
    'group.wase_title': 'ስርዓት ዋሕስ (ዋስ / ዋስትና)',
    'group.wase_desc': 'ኣብ ባህላዊ እቁብ ኢትዮጵያ፣ ዋሕስ (ዋስ) ማለት ንናይ ሓደ ኣባል ክፍሊት ንጉጅለ ዝውሕስ እሙን ሰብ እዩ። ዋስትና ዝተዋህቦ ኣባል ክፍሊት እንተድኣ ዘይኪፊሉ ዋሕስ ሓላፊ ይኸውን። ዋሕስ ነዚ እቁብ እዚ ገና ዘይተዓወተ ክኸውን ኣለዎ።',
    'group.guarantors_title': 'ንጡፋት ናይ ዋስትና ስምምዓት',
    'group.guarantors_desc': 'ነዚ ጉጅለ ናይ ዋስትና ዝምድናታት ይምሓድሩ።',
    'group.btn_assign_guarantor': 'ዋሕስ/ዋስ መድብ',
    'group.col_guarantor': 'ዋሕስ (ዋስ)',
    'group.col_guaranteed': 'ዋስትና ዝተዋህቦ ኣባል',
    'group.col_notes': 'ማስታወሻታት',
    'group.col_assigned_on': 'ዝተመደበሉ ዕለት',
    'group.status_active': 'ንጡፍ',
    'group.status_called': 'ዝተጸውዐ',
    'group.status_released': 'ዝተፈትሐ',
    'group.btn_release': 'ፍታሕ',
    'group.btn_call': 'ጸውዕ',
    'group.no_guarantors': 'ነዚ ጉጅለ ዝኾነ ናይ ዋስትና ስምምዕ የለን።',
    'group.no_guarantors_hint': 'እዚ ግዴታ ንምግባር ኣብ ደንብታት ጉጅለ "ዋሕስ የድሊ" ኣንጥፉ።',
    // Modals
    'group.modal_file_dispute': 'ምስሕሓብ ኣቕርብ',
    'group.label_dispute_type': 'ዓይነት ምስሕሓብ',
    'group.option_payment_issue': 'ናይ ክፍሊት ጸገም',
    'group.option_rule_violation': 'ምግሃስ ደንቢ',
    'group.option_lottery_issue': 'ናይ ዕጫ ጸገም',
    'group.option_other': 'ካልእ',
    'group.label_against_member': 'ኣንጻር ኣባል (ኣማራጺ)',
    'group.option_general_dispute': 'ሓፈሻዊ ናይ ጉጅለ ምስሕሓብ',
    'group.label_description': 'መግለጺ *',
    'group.placeholder_dispute': 'ነቲ ጸገም ብዝርዝር ግለጽዎ...',
    'group.btn_submit_dispute': 'ምስሕሓብ ኣቕርብ',
    'group.modal_resolve': 'ምስሕሓብ ፍታሕ',
    'group.label_resolution_notes': 'ናይ ፍታሕ ማስታወሻታት *',
    'group.placeholder_resolution': 'ናይ ፍታሕ ስጉምትታት ወይ ማስታወሻታት የእትዉ...',
    'group.btn_mark_resolved': 'ዝተፈትሐ ይገበር',
    'group.modal_request_swap': 'ናይ ዑደት ልውውጥ ሕተት',
    'group.swap_desc': 'ናይ ዝቕጽል ዕጫ ዙርያኹም ምስ ካልእ ኣባል ንምልውዋጥ ሕተቱ።',
    'group.label_target_member': 'ዒላማ ኣባል ይምረጹ *',
    'group.placeholder_select_member': 'ኣባል ይምረጹ...',
    'group.label_reason': 'ምኽንያት (ኣማራጺ)',
    'group.placeholder_swap_reason': 'ስለምንታይ ክትልውጡ ከም ዝደለኹም ግለጹ...',
    'group.btn_send_request': 'ሕቶ ስደድ',
    'group.modal_assign_guarantor': 'ዋሕስ/ዋስ መድብ',
    'group.wase_rule': 'ደንቢ ዋሕስ:',
    'group.wase_rule_desc': 'ዋሕስ ነዚ ናይ እቁብ ዑደት ገና ዘይተዓወተ ንጡፍ ኣባል ክኸውን ኣለዎ።',
    'group.label_guarantor_select': 'ዋሕስ (ዋስ) *',
    'group.placeholder_guarantor': 'ዋሕስ ኣባል ይምረጹ...',
    'group.already_won': '(ቅድሚ ሕጂ ዝተዓወተ)',
    'group.label_guaranteed_select': 'ዋስትና ዝወሃቦ ኣባል *',
    'group.placeholder_guaranteed': 'ዋስትና ዝወሃቦ ኣባል ይምረጹ...',
    'group.label_notes': 'ማስታወሻታት (ኣማራጺ)',
    'group.placeholder_notes': 'ዝኾነ ተወሳኺ መግለጺ ወይ ናይ ስምምዕ ማስታወሻታት...',
    'group.btn_assign': 'ዋሕስ መድብ',
    'group.btn_cancel': 'ሰርዝ',
    // Login page
    'login.title': 'Equb አስተዳዳሪ',
    'login.subtitle': 'ዲጂታል ቁጠባ ሲስተም',
    'login.welcome': 'እንቋዕ ብሰላም ተመለሱ',
    'login.email': 'ኣድራሻ ኢሜይል',
    'login.password': 'ምስጢራዊ ቃል',
    'login.remember': 'ዘክረኒ',
    'login.savings': 'ጉጅለታት ቁጠባ',
    'login.signin': 'እቶ',
    // Receipts extra
    'receipts.bank': 'ባንኪ',
    'receipts.bank_name': 'ሽም ባንኪ',
    'receipts.extracted_amount': 'ዝተዘርዘረ መጠን',
    // Lottery extra
    'lottery.eligible': 'ብቑዕ',
    'lottery.col_winner': 'ዓወታዊ',
    // Members extra
    'member.col_group_name': 'ሽም ጉጅለ',
    'member.col_amount_won': 'ዝተዓወተ መጠን',
    'member.save_changes': 'ለውጥታት ዓቅብ',
    // Groups list
    'groups.frequency_weekly': 'ናይ ሰሙን',
    'groups.frequency_monthly': 'ናይ ወርሒ',
    // Receipts page
    'receipts.title': 'ቅብሊት / ደረሰኝ',
    'receipts.subtitle_pending': 'ናይ ተቀማጦ ቅብሊት የረጋግጹ',
    'receipts.filter': 'መጻረዪ:',
    'receipts.all_status': 'ኹሉ ኹነታት',
    'receipts.pending': 'ዝጽበ',
    'receipts.verified': 'ዝተረጋገጸ',
    'receipts.rejected': 'ውድቅ ዝተገብረ',
    'receipts.all_groups': 'ኹሎም ጉጅለታት',
    'receipts.no_receipts': 'ቅብሊት ኣይተረኸበን',
    'receipts.no_receipts_desc': 'ነቲ መጻረዪ ዝሰማማዕ ቅብሊት ኣይተረኸበን።',
    'receipts.modal_title': 'ዝርዝር ቅብሊት',
    'receipts.ocr_title': 'ብOCR ዝተነበበ መረዳእታ',
    'receipts.ocr_mismatch': '⚠️ ፍልልይ መጠን ገንዘብ ተረኺቡ',
    'receipts.loading': 'ቅብሊት ይጽዓን ኣሎ...',
    'receipts.verify': 'አረጋግጽ',
    'receipts.reject': 'ውድቅ ግበር',
    'receipts.ocr_ref': 'ናይ ትራንዛክሽን መለለዪ',
    'receipts.ocr_date': 'ዝተነበበሉ ዕለት',
    'receipts.image_label': 'ምስሊ ናይ ደረሰኝ',
    'receipts.no_image': 'ምስሊ ኣይተጻዕነን',
    'group.save_template_as': 'ደንብታት ከም ቅጥዒ ዓቅብ',
    'group.label_max_missed': 'ዝለዓለና ዝተረፈ ክፍሊት',
    'group.label_max_missed_removal': 'ቅድሚ ምስራዝ ዝለዓለና ዝተረፈ ክፍሊት',
    // Lottery page
    'lottery.title': 'ዕጫታት እቁብ',
    'lottery.subtitle': 'ናይ እቁብ ዕጫታት ይምሓድሩን የካይዱን',
    'lottery.draw_complete': '🎉 ዕጫ ምውጻእ ተዛዚሙ!',
    'lottery.trigger_draw': 'ሓድሽ ዕጫ ኣውጽእ',
    'lottery.winner': 'ተዓዋቲ:',
    'lottery.gross_payout': 'ጠቕላላ ዓወት:',
    'lottery.admin_fee': 'ናይ ምምሕዳር ክፍያ:',
    'lottery.net_payout': 'ንኣባል ዝወሃብ ንጹር ክፍያ:',
    'lottery.draw_again': 'ድጋሚ ዕጫ ኣውጽእ',
    'lottery.select_group': 'ጉጅለ ይምረጹ',
    'lottery.choose_group': 'ጉጅለ ይምረጹ...',
    'lottery.draw_now': 'ሕጂ ዕጫ ኣውጽእ',
    'lottery.past_results': 'ናይ ዝሓለፉ ዕጫታት ውጽኢት',
    'lottery.past_results_desc': 'ናይ ኹሎም ጉጅለታት ናይ ሓለፉ ዕጫታት ታሪክ',
    'lottery.no_results': 'ክሳብ ሕጂ ዝወጸ ዕጫ የለን።',
    'lottery.loading': 'ዕጫ ይጽዓን ኣሎ...',
    // Notifications page
    'notifications.title': 'መጠንቀቅታታት',
    'notifications.subtitle': 'ናይ ጉጅለ ንጥፈታት፣ ናይ መወዳእታ ግዜን መጠንቀቅታታትን ይከታተሉ',
    'notifications.mark_all': 'ኹሉ ዝተነበበ ግበር',
    'notifications.loading': 'መጠንቀቅታታት ይጽዓኑ ኣለዉ...',
    'notifications.all_caught_up': 'ኹሎም መጠንቀቅታታት ተነቢቦም እዮም!',
    'notifications.no_read': 'ዝተነበቡ መጠንቀቅታታት የለዉን',
    'notifications.no_notifications': 'መጠንቀቅታ የለን',
    'notifications.no_unread_desc': 'ምንም ዘይተነበበ መጠንቀቅታ የብልኩምን።',
    'notifications.no_read_desc': 'ዘንበብኩምዎም መጠንቀቅታታት ኣብዚ ክርኣዩ እዮም።',
    'notifications.no_notifications_desc': 'ብዛዕባ ናይ መወዳእታ ግዜ፣ ኣታዊታትን ናይ ጉጅለ ንጥፈታትን ዝምልከቱ መጠንቀቅታታት ኣብዚ ክርኣዩ እዮ።',
    // Rule Templates Page
    'rules.title': 'ንድፊ ደንብታት',
    'rules.subtitle': 'ናይ ደንብታት ቅጥታት ኣብ ጉጅለታት ይምሓድሩን ይጥቀሙን',
    'rules.create_btn': 'ንድፊ ፍጠር',
    'rules.search_placeholder': 'ንድፍታት ብስም ወይ መግለጺ ድለዩ...',
    'rules.no_templates': 'ክሳብ ሕጂ ምንም ናይ ደንብታት ንድፍታት የለዉን',
    'rules.no_templates_desc': 'ናይ ደንብታት ቅንብራት ኣብ ጉጅለታትኩም ንምዕቃብን ደጊምኩም ንምጥቃምን ንድፊ ፍጠሩ።',
    'rules.no_templates_match': 'ምንም ዝሰማማዕ ንድፊ ኣይተረኸበን',
    'rules.no_templates_match_desc': 'ካልእ መእተዊ ቃል ፈትኑ።',
    'rules.loading': 'ንድፍታት ይጽዓኑ ኣለዉ...',
    'rules.modal_create': 'ናይ ደንብታት ንድፊ ፍጠር',
    'rules.modal_edit': 'ናይ ደንብታት ንድፊ ኣስተኻኽል',
    'rules.btn_cancel': 'ሰርዝ',
    'rules.btn_create': 'ንድፊ ፍጠር',
    'rules.btn_save': 'ለውጥታት ዕቅብ',
    'rules.label_name': 'ስም ንድፊ *',
    'rules.label_desc': 'መግለጺ',
    'rules.label_desc_placeholder': 'ናይዚ ንድፊ እዚ ሓጺር መግለጺ...',
    // Members & Member Detail Pages
    'members.title': 'አባላት መድረኽ',
    'members.subtitle': 'ኩሎም አባላት መድረኽ የመሓድሩ',
    'members.add_btn': 'አባል ወስኽ',
    'members.search_placeholder': 'ብሽም፣ ብስልኪ ወይ ብቴሌግራም መለለዪ ድለዩ...',
    'members.col_name': 'ሽም',
    'members.col_phone': 'ስልኪ',
    'members.col_telegram': 'ቴሌግራም',
    'members.col_groups': 'ጉጅለታት',
    'members.col_deposits': 'አጠቃላይ ክፍሊት',
    'members.col_joined': 'ዝተጸንበረሉ',
    'members.no_members': 'ዝተረኸበ አባል የለን',
    'members.no_members_desc': 'ክሳብ ሕጂ ዝተመዝገበ አባል የለን። ንምጅማር ቀዳማይ አባል ይወስኹ።',
    'members.no_members_match': 'ምስ ፍለጋኹም ዝተኣሳሰር አባል ኣይተረኸበን።',
    'members.modal_title': 'ሓድሽ አባል ወስኽ',
    'members.label_name': 'ምሉእ ሕጋዊ ሽም *',
    'members.label_phone': 'ቁጽሪ ስልኪ *',
    'members.label_gov_id': 'መለለዪ መንግስቲ / ዲጂታል መለለዪ',
    'members.label_telegram': 'ናይ ቴሌግራም መለለዪ',
    'members.label_photo': 'ስእሊ',
    'members.label_marital': 'ኩነታት መውስቦ',
    'members.label_employment': 'ኩነታት ስራሕ',
    'members.label_employer': 'ሽም ወሃብ ስራሕ / ትካል',
    'members.label_country': 'ዓዲ',
    'members.label_city': 'ከተማ',
    'members.label_subcity': 'ክፍለ ከተማ',
    'members.label_woreda': 'ወረዳ',
    'members.label_house': 'ቁጽሪ ገዛ',
    'members.basic_info': 'መሰረታዊ ሓበሬታ',
    'members.personal_details': 'ናይ ውልቂ ዝርዝር',
    'members.address': 'ኣድራሻ',
    'members.btn_cancel': 'ሰርዝ',
    'members.btn_add': 'አባል ወስኽ',
    'members.success_create': 'አባል ብዓወት ተወሲኹ ኣሎ!',
    'members.loading': 'አባላት ይጽዓኑ ኣለዉ...',
    'member.back': 'ናብ አባላት ተመለስ',
    'member.not_found': 'አባል ኣይተረኸበን',
    'member.not_found_desc': 'እዚ አባል የለን ወይ ተሰሪዙ እዩ።',
    'member.since': 'አባል ካብ',
    'member.edit': 'አስተኻኽል',
    'member.delete_btn': 'ተጠቃሚ ሰርዝ',
    'member.stat_wins': 'ዓወታት ዕጫ',
    'member.stat_payments': 'አጠቃላይ ክፍሊታት',
    'member.personal_info': 'ናይ ውልቂ ሓበሬታ',
    'member.tab_deposits': 'ታሪኽ ክፍሊት',
    'member.tab_groups': 'ጉጅለታት',
    'member.tab_wins': 'ዓወታት ዕጫ',
    'member.no_deposits': 'ክሳብ ሕጂ ታሪኽ ክፍሊት የለን።',
    'member.no_groups': 'ክሳብ ሕጂ ናይ ዝኾነ ጉጅለ አባል ኣይኮነን።',
    'member.no_wins': 'ክሳብ ሕጂ ዝኾነ ዓወት ዕጫ የለን።',
    'member.modal_delete': 'ተጠቃሚ ሰርዝ',
    'member.delete_warning': 'መተሓሳሰቢ፡ እዚ ስጉምቲ እዚ ክምለስ ኣይኽእልን እዩ። ታሪኽ ክፍሊትን ኣባልነት ጉጅለን ሓዊሱ ምስዚ ተጠቃሚ ዝተኣሳሰር ኩሉ ሓበሬታ ንሓዋሩ ክጠፍእ እዩ።',
    'member.delete_confirm_label': 'ንምርግጋጽ ናይ አስተዳዳሪ ምስጢራዊ ቃል የእትዉ',
    'member.placeholder_pwd': 'ናይ አስተዳዳሪ ምስጢራዊ ቃል',
    'member.modal_edit': 'አባል አስተኻኽል',
    'member.btn_save': 'ለውጥታት ዓቅብ',
    'member.success_update': 'ሓበሬታ አባል ብዓወት ተመሓይሹ ኣሎ!',
    'member.loading_detail': 'ዝርዝር ሓበሬታ አባል ይጽዓን ኣሎ...',
    // Shares & Group Assignment
    'groups.label_amount_per_share': 'አስተዋፅኦ ንሓደ ብጽሒት (ETB)',
    'groups.amount_per_share_hint': 'ነፍሲ ወከፍ ኣባል ንሓደ ምሉእ ብጽሒት ኣብ ዙርያ ዝኸፍሎ መጠን',
    'members.group_assignment': 'ምደባ ጉጅለ (ኣማራጺ)',
    'members.label_select_group': 'ጉጅለ ይምረጹ',
    'members.label_shares': 'መጠን ብጽሒት',
    'members.share_quarter': 'ርብዒ (25%)',
    'members.share_half': 'ፍርቂ (50%)',
    'members.share_three_quarter': 'ሰለስተ ርብዒ (75%)',
    'members.share_full': 'ምሉእ (100%)',
    'members.expected_contribution': 'ትጽቢት ዝግበረሉ አስተዋፅኦ',
    'members.share_preview': 'እዚ ኣባል ኣብ ዙርያ ETB {amount} ክኸፍል እዩ',
    'member.col_shares': 'ብጽሒታት',
    'member.col_expected': 'ትጽቢት ኣብ ዙርያ',
    'member.edit_shares': 'ብጽሒት ኣስተኻኽል',
    'member.shares_updated': 'ብጽሒት ብዓወት ተመሓይሹ ኣሎ!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('equb_lang') as Language;
    if (saved && ['en', 'am', 'om', 'ti'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('equb_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
